### YamlMime:ManagedReference
items:
- uid: Application.Tags.Queries.ExportTags
  commentId: N:Application.Tags.Queries.ExportTags
  id: Application.Tags.Queries.ExportTags
  children:
  - Application.Tags.Queries.ExportTags.ExportTagsQuery
  - Application.Tags.Queries.ExportTags.ExportTagsQueryHandler
  - Application.Tags.Queries.ExportTags.ExportTagsQueryResult
  langs:
  - csharp
  - vb
  name: Application.Tags.Queries.ExportTags
  nameWithType: Application.Tags.Queries.ExportTags
  fullName: Application.Tags.Queries.ExportTags
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Tags.Queries.ExportTags.ExportTagsQuery
  commentId: T:Application.Tags.Queries.ExportTags.ExportTagsQuery
  parent: Application.Tags.Queries.ExportTags
  href: Application.Tags.Queries.ExportTags.ExportTagsQuery.html
  name: ExportTagsQuery
  nameWithType: ExportTagsQuery
  fullName: Application.Tags.Queries.ExportTags.ExportTagsQuery
- uid: Application.Tags.Queries.ExportTags.ExportTagsQueryHandler
  commentId: T:Application.Tags.Queries.ExportTags.ExportTagsQueryHandler
  href: Application.Tags.Queries.ExportTags.ExportTagsQueryHandler.html
  name: ExportTagsQueryHandler
  nameWithType: ExportTagsQueryHandler
  fullName: Application.Tags.Queries.ExportTags.ExportTagsQueryHandler
- uid: Application.Tags.Queries.ExportTags.ExportTagsQueryResult
  commentId: T:Application.Tags.Queries.ExportTags.ExportTagsQueryResult
  href: Application.Tags.Queries.ExportTags.ExportTagsQueryResult.html
  name: ExportTagsQueryResult
  nameWithType: ExportTagsQueryResult
  fullName: Application.Tags.Queries.ExportTags.ExportTagsQueryResult
- uid: Application.Tags.Queries.ExportTags
  commentId: N:Application.Tags.Queries.ExportTags
  href: Application.html
  name: Application.Tags.Queries.ExportTags
  nameWithType: Application.Tags.Queries.ExportTags
  fullName: Application.Tags.Queries.ExportTags
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Tags
    name: Tags
    href: Application.Tags.html
  - name: .
  - uid: Application.Tags.Queries
    name: Queries
    href: Application.Tags.Queries.html
  - name: .
  - uid: Application.Tags.Queries.ExportTags
    name: ExportTags
    href: Application.Tags.Queries.ExportTags.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Tags
    name: Tags
    href: Application.Tags.html
  - name: .
  - uid: Application.Tags.Queries
    name: Queries
    href: Application.Tags.Queries.html
  - name: .
  - uid: Application.Tags.Queries.ExportTags
    name: ExportTags
    href: Application.Tags.Queries.ExportTags.html
