### YamlMime:ManagedReference
items:
- uid: Application.Commons.Extensions.LoggingLevelController
  commentId: T:Application.Commons.Extensions.LoggingLevelController
  id: LoggingLevelController
  parent: Application.Commons.Extensions
  children:
  - Application.Commons.Extensions.LoggingLevelController.LevelSwitch
  langs:
  - csharp
  - vb
  name: LoggingLevelController
  nameWithType: LoggingLevelController
  fullName: Application.Commons.Extensions.LoggingLevelController
  type: Class
  source:
    remote:
      path: src/Application/Commons/Extensions/LoggingLevelSwitch.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: LoggingLevelController
    path: src/Application/Commons/Extensions/LoggingLevelSwitch.cs
    startLine: 5
  assemblies:
  - Application
  namespace: Application.Commons.Extensions
  syntax:
    content: public static class LoggingLevelController
    content.vb: Public Module LoggingLevelController
  inheritance:
  - System.Object
- uid: Application.Commons.Extensions.LoggingLevelController.LevelSwitch
  commentId: F:Application.Commons.Extensions.LoggingLevelController.LevelSwitch
  id: LevelSwitch
  parent: Application.Commons.Extensions.LoggingLevelController
  langs:
  - csharp
  - vb
  name: LevelSwitch
  nameWithType: LoggingLevelController.LevelSwitch
  fullName: Application.Commons.Extensions.LoggingLevelController.LevelSwitch
  type: Field
  source:
    remote:
      path: src/Application/Commons/Extensions/LoggingLevelSwitch.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: LevelSwitch
    path: src/Application/Commons/Extensions/LoggingLevelSwitch.cs
    startLine: 7
  assemblies:
  - Application
  namespace: Application.Commons.Extensions
  syntax:
    content: public static readonly LoggingLevelSwitch LevelSwitch
    return:
      type: Serilog.Core.LoggingLevelSwitch
    content.vb: Public Shared ReadOnly LevelSwitch As LoggingLevelSwitch
references:
- uid: Application.Commons.Extensions
  commentId: N:Application.Commons.Extensions
  href: Application.html
  name: Application.Commons.Extensions
  nameWithType: Application.Commons.Extensions
  fullName: Application.Commons.Extensions
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Extensions
    name: Extensions
    href: Application.Commons.Extensions.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Extensions
    name: Extensions
    href: Application.Commons.Extensions.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Serilog.Core.LoggingLevelSwitch
  commentId: T:Serilog.Core.LoggingLevelSwitch
  parent: Serilog.Core
  isExternal: true
  name: LoggingLevelSwitch
  nameWithType: LoggingLevelSwitch
  fullName: Serilog.Core.LoggingLevelSwitch
- uid: Serilog.Core
  commentId: N:Serilog.Core
  isExternal: true
  name: Serilog.Core
  nameWithType: Serilog.Core
  fullName: Serilog.Core
  spec.csharp:
  - uid: Serilog
    name: Serilog
    isExternal: true
  - name: .
  - uid: Serilog.Core
    name: Core
    isExternal: true
  spec.vb:
  - uid: Serilog
    name: Serilog
    isExternal: true
  - name: .
  - uid: Serilog.Core
    name: Core
    isExternal: true
