### YamlMime:ManagedReference
items:
- uid: Application.Sources.Queries.GetAllSources
  commentId: N:Application.Sources.Queries.GetAllSources
  id: Application.Sources.Queries.GetAllSources
  children:
  - Application.Sources.Queries.GetAllSources.GetAllSourceQuery
  - Application.Sources.Queries.GetAllSources.GetAllSourceQueryHandler
  - Application.Sources.Queries.GetAllSources.GetAllSourceQueryResult
  langs:
  - csharp
  - vb
  name: Application.Sources.Queries.GetAllSources
  nameWithType: Application.Sources.Queries.GetAllSources
  fullName: Application.Sources.Queries.GetAllSources
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Sources.Queries.GetAllSources.GetAllSourceQuery
  commentId: T:Application.Sources.Queries.GetAllSources.GetAllSourceQuery
  parent: Application.Sources.Queries.GetAllSources
  href: Application.Sources.Queries.GetAllSources.GetAllSourceQuery.html
  name: GetAllSourceQuery
  nameWithType: GetAllSourceQuery
  fullName: Application.Sources.Queries.GetAllSources.GetAllSourceQuery
- uid: Application.Sources.Queries.GetAllSources.GetAllSourceQueryHandler
  commentId: T:Application.Sources.Queries.GetAllSources.GetAllSourceQueryHandler
  href: Application.Sources.Queries.GetAllSources.GetAllSourceQueryHandler.html
  name: GetAllSourceQueryHandler
  nameWithType: GetAllSourceQueryHandler
  fullName: Application.Sources.Queries.GetAllSources.GetAllSourceQueryHandler
- uid: Application.Sources.Queries.GetAllSources.GetAllSourceQueryResult
  commentId: T:Application.Sources.Queries.GetAllSources.GetAllSourceQueryResult
  href: Application.Sources.Queries.GetAllSources.GetAllSourceQueryResult.html
  name: GetAllSourceQueryResult
  nameWithType: GetAllSourceQueryResult
  fullName: Application.Sources.Queries.GetAllSources.GetAllSourceQueryResult
- uid: Application.Sources.Queries.GetAllSources
  commentId: N:Application.Sources.Queries.GetAllSources
  href: Application.html
  name: Application.Sources.Queries.GetAllSources
  nameWithType: Application.Sources.Queries.GetAllSources
  fullName: Application.Sources.Queries.GetAllSources
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Sources
    name: Sources
    href: Application.Sources.html
  - name: .
  - uid: Application.Sources.Queries
    name: Queries
    href: Application.Sources.Queries.html
  - name: .
  - uid: Application.Sources.Queries.GetAllSources
    name: GetAllSources
    href: Application.Sources.Queries.GetAllSources.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Sources
    name: Sources
    href: Application.Sources.html
  - name: .
  - uid: Application.Sources.Queries
    name: Queries
    href: Application.Sources.Queries.html
  - name: .
  - uid: Application.Sources.Queries.GetAllSources
    name: GetAllSources
    href: Application.Sources.Queries.GetAllSources.html
