### YamlMime:ManagedReference
items:
- uid: Application.Categories.Commands.UpdateCategoryParentReference
  commentId: N:Application.Categories.Commands.UpdateCategoryParentReference
  id: Application.Categories.Commands.UpdateCategoryParentReference
  children:
  - Application.Categories.Commands.UpdateCategoryParentReference.UpdateCategoryParentRefrenceCommand
  langs:
  - csharp
  - vb
  name: Application.Categories.Commands.UpdateCategoryParentReference
  nameWithType: Application.Categories.Commands.UpdateCategoryParentReference
  fullName: Application.Categories.Commands.UpdateCategoryParentReference
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Categories.Commands.UpdateCategoryParentReference.UpdateCategoryParentRefrenceCommand
  commentId: T:Application.Categories.Commands.UpdateCategoryParentReference.UpdateCategoryParentRefrenceCommand
  href: Application.Categories.Commands.UpdateCategoryParentReference.UpdateCategoryParentRefrenceCommand.html
  name: UpdateCategoryParentRefrenceCommand
  nameWithType: UpdateCategoryParentRefrenceCommand
  fullName: Application.Categories.Commands.UpdateCategoryParentReference.UpdateCategoryParentRefrenceCommand
