### YamlMime:ManagedReference
items:
- uid: Application.Commons.SharedModelResult.Timeline.EntityTimeline
  commentId: N:Application.Commons.SharedModelResult.Timeline.EntityTimeline
  id: Application.Commons.SharedModelResult.Timeline.EntityTimeline
  children:
  - Application.Commons.SharedModelResult.Timeline.EntityTimeline.TimelineQueryResult
  langs:
  - csharp
  - vb
  name: Application.Commons.SharedModelResult.Timeline.EntityTimeline
  nameWithType: Application.Commons.SharedModelResult.Timeline.EntityTimeline
  fullName: Application.Commons.SharedModelResult.Timeline.EntityTimeline
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Commons.SharedModelResult.Timeline.EntityTimeline.TimelineQueryResult
  commentId: T:Application.Commons.SharedModelResult.Timeline.EntityTimeline.TimelineQueryResult
  href: Application.Commons.SharedModelResult.Timeline.EntityTimeline.TimelineQueryResult.html
  name: TimelineQueryResult
  nameWithType: TimelineQueryResult
  fullName: Application.Commons.SharedModelResult.Timeline.EntityTimeline.TimelineQueryResult
