### YamlMime:ManagedReference
items:
- uid: Application.Commons.Validation.Pagination
  commentId: N:Application.Commons.Validation.Pagination
  id: Application.Commons.Validation.Pagination
  children:
  - Application.Commons.Validation.Pagination.PageRequestValidator
  langs:
  - csharp
  - vb
  name: Application.Commons.Validation.Pagination
  nameWithType: Application.Commons.Validation.Pagination
  fullName: Application.Commons.Validation.Pagination
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Commons.Validation.Pagination.PageRequestValidator
  commentId: T:Application.Commons.Validation.Pagination.PageRequestValidator
  href: Application.Commons.Validation.Pagination.PageRequestValidator.html
  name: PageRequestValidator
  nameWithType: PageRequestValidator
  fullName: Application.Commons.Validation.Pagination.PageRequestValidator
