### YamlMime:ManagedReference
items:
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult
  commentId: T:Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult
  id: MultipleChoiseQuestionResult
  parent: Application.Questions.Queries.GetQuestionsById.ResultModel
  children:
  - Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.FeedBack
  - Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Id
  - Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.IsCorrect
  - Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.OptionText
  - Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Weight
  langs:
  - csharp
  - vb
  name: MultipleChoiseQuestionResult
  nameWithType: MultipleChoiseQuestionResult
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult
  type: Class
  source:
    remote:
      path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/MultipleChoiseQuestionResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: MultipleChoiseQuestionResult
    path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/MultipleChoiseQuestionResult.cs
    startLine: 2
  assemblies:
  - Application
  namespace: Application.Questions.Queries.GetQuestionsById.ResultModel
  syntax:
    content: public class MultipleChoiseQuestionResult
    content.vb: Public Class MultipleChoiseQuestionResult
  inheritance:
  - System.Object
  extensionMethods:
  - System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  - System.Object.Domain.Extentions.ObjectExtention.IsNull
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Id
  commentId: P:Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Id
  id: Id
  parent: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: MultipleChoiseQuestionResult.Id
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Id
  type: Property
  source:
    remote:
      path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/MultipleChoiseQuestionResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Id
    path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/MultipleChoiseQuestionResult.cs
    startLine: 4
  assemblies:
  - Application
  namespace: Application.Questions.Queries.GetQuestionsById.ResultModel
  syntax:
    content: public Guid Id { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property Id As Guid
  overload: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Id*
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.OptionText
  commentId: P:Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.OptionText
  id: OptionText
  parent: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult
  langs:
  - csharp
  - vb
  name: OptionText
  nameWithType: MultipleChoiseQuestionResult.OptionText
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.OptionText
  type: Property
  source:
    remote:
      path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/MultipleChoiseQuestionResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: OptionText
    path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/MultipleChoiseQuestionResult.cs
    startLine: 5
  assemblies:
  - Application
  namespace: Application.Questions.Queries.GetQuestionsById.ResultModel
  syntax:
    content: public string OptionText { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property OptionText As String
  overload: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.OptionText*
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.IsCorrect
  commentId: P:Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.IsCorrect
  id: IsCorrect
  parent: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult
  langs:
  - csharp
  - vb
  name: IsCorrect
  nameWithType: MultipleChoiseQuestionResult.IsCorrect
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.IsCorrect
  type: Property
  source:
    remote:
      path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/MultipleChoiseQuestionResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: IsCorrect
    path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/MultipleChoiseQuestionResult.cs
    startLine: 6
  assemblies:
  - Application
  namespace: Application.Questions.Queries.GetQuestionsById.ResultModel
  syntax:
    content: public bool IsCorrect { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsCorrect As Boolean
  overload: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.IsCorrect*
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Weight
  commentId: P:Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Weight
  id: Weight
  parent: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult
  langs:
  - csharp
  - vb
  name: Weight
  nameWithType: MultipleChoiseQuestionResult.Weight
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Weight
  type: Property
  source:
    remote:
      path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/MultipleChoiseQuestionResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Weight
    path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/MultipleChoiseQuestionResult.cs
    startLine: 7
  assemblies:
  - Application
  namespace: Application.Questions.Queries.GetQuestionsById.ResultModel
  syntax:
    content: public float Weight { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property Weight As Single
  overload: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Weight*
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.FeedBack
  commentId: P:Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.FeedBack
  id: FeedBack
  parent: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult
  langs:
  - csharp
  - vb
  name: FeedBack
  nameWithType: MultipleChoiseQuestionResult.FeedBack
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.FeedBack
  type: Property
  source:
    remote:
      path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/MultipleChoiseQuestionResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: FeedBack
    path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/MultipleChoiseQuestionResult.cs
    startLine: 8
  assemblies:
  - Application
  namespace: Application.Questions.Queries.GetQuestionsById.ResultModel
  syntax:
    content: public string? FeedBack { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property FeedBack As String
  overload: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.FeedBack*
references:
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel
  commentId: N:Application.Questions.Queries.GetQuestionsById.ResultModel
  href: Application.html
  name: Application.Questions.Queries.GetQuestionsById.ResultModel
  nameWithType: Application.Questions.Queries.GetQuestionsById.ResultModel
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Questions
    name: Questions
    href: Application.Questions.html
  - name: .
  - uid: Application.Questions.Queries
    name: Queries
    href: Application.Questions.Queries.html
  - name: .
  - uid: Application.Questions.Queries.GetQuestionsById
    name: GetQuestionsById
    href: Application.Questions.Queries.GetQuestionsById.html
  - name: .
  - uid: Application.Questions.Queries.GetQuestionsById.ResultModel
    name: ResultModel
    href: Application.Questions.Queries.GetQuestionsById.ResultModel.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Questions
    name: Questions
    href: Application.Questions.html
  - name: .
  - uid: Application.Questions.Queries
    name: Queries
    href: Application.Questions.Queries.html
  - name: .
  - uid: Application.Questions.Queries.GetQuestionsById
    name: GetQuestionsById
    href: Application.Questions.Queries.GetQuestionsById.html
  - name: .
  - uid: Application.Questions.Queries.GetQuestionsById.ResultModel
    name: ResultModel
    href: Application.Questions.Queries.GetQuestionsById.ResultModel.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions.ObjectExtention
  commentId: T:Domain.Extentions.ObjectExtention
  parent: Domain.Extentions
  href: Domain.Extentions.ObjectExtention.html
  name: ObjectExtention
  nameWithType: ObjectExtention
  fullName: Domain.Extentions.ObjectExtention
- uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions
  commentId: N:Domain.Extentions
  href: Domain.html
  name: Domain.Extentions
  nameWithType: Domain.Extentions
  fullName: Domain.Extentions
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Id*
  commentId: Overload:Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Id
  href: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.html#Application_Questions_Queries_GetQuestionsById_ResultModel_MultipleChoiseQuestionResult_Id
  name: Id
  nameWithType: MultipleChoiseQuestionResult.Id
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Id
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.OptionText*
  commentId: Overload:Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.OptionText
  href: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.html#Application_Questions_Queries_GetQuestionsById_ResultModel_MultipleChoiseQuestionResult_OptionText
  name: OptionText
  nameWithType: MultipleChoiseQuestionResult.OptionText
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.OptionText
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.IsCorrect*
  commentId: Overload:Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.IsCorrect
  href: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.html#Application_Questions_Queries_GetQuestionsById_ResultModel_MultipleChoiseQuestionResult_IsCorrect
  name: IsCorrect
  nameWithType: MultipleChoiseQuestionResult.IsCorrect
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.IsCorrect
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Weight*
  commentId: Overload:Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Weight
  href: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.html#Application_Questions_Queries_GetQuestionsById_ResultModel_MultipleChoiseQuestionResult_Weight
  name: Weight
  nameWithType: MultipleChoiseQuestionResult.Weight
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.Weight
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.FeedBack*
  commentId: Overload:Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.FeedBack
  href: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.html#Application_Questions_Queries_GetQuestionsById_ResultModel_MultipleChoiseQuestionResult_FeedBack
  name: FeedBack
  nameWithType: MultipleChoiseQuestionResult.FeedBack
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.MultipleChoiseQuestionResult.FeedBack
