### YamlMime:ManagedReference
items:
- uid: Application.Commons.SharedModelResult.Source.MetadataResult
  commentId: T:Application.Commons.SharedModelResult.Source.MetadataResult
  id: MetadataResult
  parent: Application.Commons.SharedModelResult.Source
  children:
  - Application.Commons.SharedModelResult.Source.MetadataResult.FiledName
  - Application.Commons.SharedModelResult.Source.MetadataResult.FiledType
  - Application.Commons.SharedModelResult.Source.MetadataResult.Id
  - Application.Commons.SharedModelResult.Source.MetadataResult.Value
  langs:
  - csharp
  - vb
  name: MetadataResult
  nameWithType: MetadataResult
  fullName: Application.Commons.SharedModelResult.Source.MetadataResult
  type: Class
  source:
    remote:
      path: src/Application/Commons/SharedModelResult/Source/MetadataResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: MetadataResult
    path: src/Application/Commons/SharedModelResult/Source/MetadataResult.cs
    startLine: 4
  assemblies:
  - Application
  namespace: Application.Commons.SharedModelResult.Source
  syntax:
    content: public class MetadataResult
    content.vb: Public Class MetadataResult
  inheritance:
  - System.Object
  extensionMethods:
  - System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  - System.Object.Domain.Extentions.ObjectExtention.IsNull
- uid: Application.Commons.SharedModelResult.Source.MetadataResult.Id
  commentId: P:Application.Commons.SharedModelResult.Source.MetadataResult.Id
  id: Id
  parent: Application.Commons.SharedModelResult.Source.MetadataResult
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: MetadataResult.Id
  fullName: Application.Commons.SharedModelResult.Source.MetadataResult.Id
  type: Property
  source:
    remote:
      path: src/Application/Commons/SharedModelResult/Source/MetadataResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Id
    path: src/Application/Commons/SharedModelResult/Source/MetadataResult.cs
    startLine: 6
  assemblies:
  - Application
  namespace: Application.Commons.SharedModelResult.Source
  syntax:
    content: public Guid Id { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property Id As Guid
  overload: Application.Commons.SharedModelResult.Source.MetadataResult.Id*
- uid: Application.Commons.SharedModelResult.Source.MetadataResult.FiledName
  commentId: P:Application.Commons.SharedModelResult.Source.MetadataResult.FiledName
  id: FiledName
  parent: Application.Commons.SharedModelResult.Source.MetadataResult
  langs:
  - csharp
  - vb
  name: FiledName
  nameWithType: MetadataResult.FiledName
  fullName: Application.Commons.SharedModelResult.Source.MetadataResult.FiledName
  type: Property
  source:
    remote:
      path: src/Application/Commons/SharedModelResult/Source/MetadataResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: FiledName
    path: src/Application/Commons/SharedModelResult/Source/MetadataResult.cs
    startLine: 7
  assemblies:
  - Application
  namespace: Application.Commons.SharedModelResult.Source
  syntax:
    content: public string FiledName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property FiledName As String
  overload: Application.Commons.SharedModelResult.Source.MetadataResult.FiledName*
- uid: Application.Commons.SharedModelResult.Source.MetadataResult.Value
  commentId: P:Application.Commons.SharedModelResult.Source.MetadataResult.Value
  id: Value
  parent: Application.Commons.SharedModelResult.Source.MetadataResult
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: MetadataResult.Value
  fullName: Application.Commons.SharedModelResult.Source.MetadataResult.Value
  type: Property
  source:
    remote:
      path: src/Application/Commons/SharedModelResult/Source/MetadataResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Value
    path: src/Application/Commons/SharedModelResult/Source/MetadataResult.cs
    startLine: 8
  assemblies:
  - Application
  namespace: Application.Commons.SharedModelResult.Source
  syntax:
    content: public string Value { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Value As String
  overload: Application.Commons.SharedModelResult.Source.MetadataResult.Value*
- uid: Application.Commons.SharedModelResult.Source.MetadataResult.FiledType
  commentId: P:Application.Commons.SharedModelResult.Source.MetadataResult.FiledType
  id: FiledType
  parent: Application.Commons.SharedModelResult.Source.MetadataResult
  langs:
  - csharp
  - vb
  name: FiledType
  nameWithType: MetadataResult.FiledType
  fullName: Application.Commons.SharedModelResult.Source.MetadataResult.FiledType
  type: Property
  source:
    remote:
      path: src/Application/Commons/SharedModelResult/Source/MetadataResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: FiledType
    path: src/Application/Commons/SharedModelResult/Source/MetadataResult.cs
    startLine: 9
  assemblies:
  - Application
  namespace: Application.Commons.SharedModelResult.Source
  syntax:
    content: public FiledType FiledType { get; set; }
    parameters: []
    return:
      type: Domain.Enums.FiledType
    content.vb: Public Property FiledType As FiledType
  overload: Application.Commons.SharedModelResult.Source.MetadataResult.FiledType*
references:
- uid: Application.Commons.SharedModelResult.Source
  commentId: N:Application.Commons.SharedModelResult.Source
  href: Application.html
  name: Application.Commons.SharedModelResult.Source
  nameWithType: Application.Commons.SharedModelResult.Source
  fullName: Application.Commons.SharedModelResult.Source
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.SharedModelResult
    name: SharedModelResult
    href: Application.Commons.SharedModelResult.html
  - name: .
  - uid: Application.Commons.SharedModelResult.Source
    name: Source
    href: Application.Commons.SharedModelResult.Source.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.SharedModelResult
    name: SharedModelResult
    href: Application.Commons.SharedModelResult.html
  - name: .
  - uid: Application.Commons.SharedModelResult.Source
    name: Source
    href: Application.Commons.SharedModelResult.Source.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions.ObjectExtention
  commentId: T:Domain.Extentions.ObjectExtention
  parent: Domain.Extentions
  href: Domain.Extentions.ObjectExtention.html
  name: ObjectExtention
  nameWithType: ObjectExtention
  fullName: Domain.Extentions.ObjectExtention
- uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions
  commentId: N:Domain.Extentions
  href: Domain.html
  name: Domain.Extentions
  nameWithType: Domain.Extentions
  fullName: Domain.Extentions
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
- uid: Application.Commons.SharedModelResult.Source.MetadataResult.Id*
  commentId: Overload:Application.Commons.SharedModelResult.Source.MetadataResult.Id
  href: Application.Commons.SharedModelResult.Source.MetadataResult.html#Application_Commons_SharedModelResult_Source_MetadataResult_Id
  name: Id
  nameWithType: MetadataResult.Id
  fullName: Application.Commons.SharedModelResult.Source.MetadataResult.Id
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: Application.Commons.SharedModelResult.Source.MetadataResult.FiledName*
  commentId: Overload:Application.Commons.SharedModelResult.Source.MetadataResult.FiledName
  href: Application.Commons.SharedModelResult.Source.MetadataResult.html#Application_Commons_SharedModelResult_Source_MetadataResult_FiledName
  name: FiledName
  nameWithType: MetadataResult.FiledName
  fullName: Application.Commons.SharedModelResult.Source.MetadataResult.FiledName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Application.Commons.SharedModelResult.Source.MetadataResult.Value*
  commentId: Overload:Application.Commons.SharedModelResult.Source.MetadataResult.Value
  href: Application.Commons.SharedModelResult.Source.MetadataResult.html#Application_Commons_SharedModelResult_Source_MetadataResult_Value
  name: Value
  nameWithType: MetadataResult.Value
  fullName: Application.Commons.SharedModelResult.Source.MetadataResult.Value
- uid: Application.Commons.SharedModelResult.Source.MetadataResult.FiledType*
  commentId: Overload:Application.Commons.SharedModelResult.Source.MetadataResult.FiledType
  href: Application.Commons.SharedModelResult.Source.MetadataResult.html#Application_Commons_SharedModelResult_Source_MetadataResult_FiledType
  name: FiledType
  nameWithType: MetadataResult.FiledType
  fullName: Application.Commons.SharedModelResult.Source.MetadataResult.FiledType
- uid: Domain.Enums.FiledType
  commentId: T:Domain.Enums.FiledType
  parent: Domain.Enums
  href: Domain.Enums.FiledType.html
  name: FiledType
  nameWithType: FiledType
  fullName: Domain.Enums.FiledType
- uid: Domain.Enums
  commentId: N:Domain.Enums
  href: Domain.html
  name: Domain.Enums
  nameWithType: Domain.Enums
  fullName: Domain.Enums
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Enums
    name: Enums
    href: Domain.Enums.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Enums
    name: Enums
    href: Domain.Enums.html
