### YamlMime:ManagedReference
items:
- uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  commentId: N:Application.EntitlesTimeline.Queries.EntityTimelineDetails
  id: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  children:
  - Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery
  - Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQueryHandler
  langs:
  - csharp
  - vb
  name: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  nameWithType: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  fullName: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery
  commentId: T:Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery
  parent: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  href: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.html
  name: EntityTimelineDetailsQuery
  nameWithType: EntityTimelineDetailsQuery
  fullName: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery
- uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQueryHandler
  commentId: T:Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQueryHandler
  href: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQueryHandler.html
  name: EntityTimelineDetailsQueryHandler
  nameWithType: EntityTimelineDetailsQueryHandler
  fullName: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQueryHandler
- uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  commentId: N:Application.EntitlesTimeline.Queries.EntityTimelineDetails
  href: Application.html
  name: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  nameWithType: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  fullName: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.EntitlesTimeline
    name: EntitlesTimeline
    href: Application.EntitlesTimeline.html
  - name: .
  - uid: Application.EntitlesTimeline.Queries
    name: Queries
    href: Application.EntitlesTimeline.Queries.html
  - name: .
  - uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails
    name: EntityTimelineDetails
    href: Application.EntitlesTimeline.Queries.EntityTimelineDetails.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.EntitlesTimeline
    name: EntitlesTimeline
    href: Application.EntitlesTimeline.html
  - name: .
  - uid: Application.EntitlesTimeline.Queries
    name: Queries
    href: Application.EntitlesTimeline.Queries.html
  - name: .
  - uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails
    name: EntityTimelineDetails
    href: Application.EntitlesTimeline.Queries.EntityTimelineDetails.html
