### YamlMime:ManagedReference
items:
- uid: Application.Lookups.Commands.Sources.UpdateSource
  commentId: N:Application.Lookups.Commands.Sources.UpdateSource
  id: Application.Lookups.Commands.Sources.UpdateSource
  children:
  - Application.Lookups.Commands.Sources.UpdateSource.UpdateSourceCommand
  - Application.Lookups.Commands.Sources.UpdateSource.UpdateSourceCommandHandler
  langs:
  - csharp
  - vb
  name: Application.Lookups.Commands.Sources.UpdateSource
  nameWithType: Application.Lookups.Commands.Sources.UpdateSource
  fullName: Application.Lookups.Commands.Sources.UpdateSource
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Lookups.Commands.Sources.UpdateSource.UpdateSourceCommand
  commentId: T:Application.Lookups.Commands.Sources.UpdateSource.UpdateSourceCommand
  parent: Application.Lookups.Commands.Sources.UpdateSource
  href: Application.Lookups.Commands.Sources.UpdateSource.UpdateSourceCommand.html
  name: UpdateSourceCommand
  nameWithType: UpdateSourceCommand
  fullName: Application.Lookups.Commands.Sources.UpdateSource.UpdateSourceCommand
- uid: Application.Lookups.Commands.Sources.UpdateSource.UpdateSourceCommandHandler
  commentId: T:Application.Lookups.Commands.Sources.UpdateSource.UpdateSourceCommandHandler
  href: Application.Lookups.Commands.Sources.UpdateSource.UpdateSourceCommandHandler.html
  name: UpdateSourceCommandHandler
  nameWithType: UpdateSourceCommandHandler
  fullName: Application.Lookups.Commands.Sources.UpdateSource.UpdateSourceCommandHandler
- uid: Application.Lookups.Commands.Sources.UpdateSource
  commentId: N:Application.Lookups.Commands.Sources.UpdateSource
  href: Application.html
  name: Application.Lookups.Commands.Sources.UpdateSource
  nameWithType: Application.Lookups.Commands.Sources.UpdateSource
  fullName: Application.Lookups.Commands.Sources.UpdateSource
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Lookups
    name: Lookups
    href: Application.Lookups.html
  - name: .
  - uid: Application.Lookups.Commands
    name: Commands
    href: Application.Lookups.Commands.html
  - name: .
  - uid: Application.Lookups.Commands.Sources
    name: Sources
    href: Application.Lookups.Commands.Sources.html
  - name: .
  - uid: Application.Lookups.Commands.Sources.UpdateSource
    name: UpdateSource
    href: Application.Lookups.Commands.Sources.UpdateSource.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Lookups
    name: Lookups
    href: Application.Lookups.html
  - name: .
  - uid: Application.Lookups.Commands
    name: Commands
    href: Application.Lookups.Commands.html
  - name: .
  - uid: Application.Lookups.Commands.Sources
    name: Sources
    href: Application.Lookups.Commands.Sources.html
  - name: .
  - uid: Application.Lookups.Commands.Sources.UpdateSource
    name: UpdateSource
    href: Application.Lookups.Commands.Sources.UpdateSource.html
