### YamlMime:ManagedReference
items:
- uid: Application.Commons.Services.ICategoryService
  commentId: T:Application.Commons.Services.ICategoryService
  id: ICategoryService
  parent: Application.Commons.Services
  children:
  - Application.Commons.Services.ICategoryService.AddCategory(System.String,System.String,System.Nullable{System.Guid})
  - Application.Commons.Services.ICategoryService.UpdateCategory(System.Guid,System.String,System.String)
  langs:
  - csharp
  - vb
  name: ICategoryService
  nameWithType: ICategoryService
  fullName: Application.Commons.Services.ICategoryService
  type: Interface
  source:
    remote:
      path: src/Application/Commons/Services/ICategoryService.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: ICategoryService
    path: src/Application/Commons/Services/ICategoryService.cs
    startLine: 5
  assemblies:
  - Application
  namespace: Application.Commons.Services
  syntax:
    content: public interface ICategoryService
    content.vb: Public Interface ICategoryService
  extensionMethods:
  - System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  - System.Object.Domain.Extentions.ObjectExtention.IsNull
- uid: Application.Commons.Services.ICategoryService.AddCategory(System.String,System.String,System.Nullable{System.Guid})
  commentId: M:Application.Commons.Services.ICategoryService.AddCategory(System.String,System.String,System.Nullable{System.Guid})
  id: AddCategory(System.String,System.String,System.Nullable{System.Guid})
  parent: Application.Commons.Services.ICategoryService
  langs:
  - csharp
  - vb
  name: AddCategory(string, string, Guid?)
  nameWithType: ICategoryService.AddCategory(string, string, Guid?)
  fullName: Application.Commons.Services.ICategoryService.AddCategory(string, string, System.Guid?)
  type: Method
  source:
    remote:
      path: src/Application/Commons/Services/ICategoryService.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: AddCategory
    path: src/Application/Commons/Services/ICategoryService.cs
    startLine: 7
  assemblies:
  - Application
  namespace: Application.Commons.Services
  syntax:
    content: Result<Category> AddCategory(string name, string description, Guid? parentId)
    parameters:
    - id: name
      type: System.String
    - id: description
      type: System.String
    - id: parentId
      type: System.Nullable{System.Guid}
    return:
      type: Application.Commons.Models.Results.Result{Domain.Entities.EntityLookup.Category}
    content.vb: Function AddCategory(name As String, description As String, parentId As Guid?) As Result(Of Category)
  overload: Application.Commons.Services.ICategoryService.AddCategory*
  nameWithType.vb: ICategoryService.AddCategory(String, String, Guid?)
  fullName.vb: Application.Commons.Services.ICategoryService.AddCategory(String, String, System.Guid?)
  name.vb: AddCategory(String, String, Guid?)
- uid: Application.Commons.Services.ICategoryService.UpdateCategory(System.Guid,System.String,System.String)
  commentId: M:Application.Commons.Services.ICategoryService.UpdateCategory(System.Guid,System.String,System.String)
  id: UpdateCategory(System.Guid,System.String,System.String)
  parent: Application.Commons.Services.ICategoryService
  langs:
  - csharp
  - vb
  name: UpdateCategory(Guid, string, string)
  nameWithType: ICategoryService.UpdateCategory(Guid, string, string)
  fullName: Application.Commons.Services.ICategoryService.UpdateCategory(System.Guid, string, string)
  type: Method
  source:
    remote:
      path: src/Application/Commons/Services/ICategoryService.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: UpdateCategory
    path: src/Application/Commons/Services/ICategoryService.cs
    startLine: 8
  assemblies:
  - Application
  namespace: Application.Commons.Services
  syntax:
    content: Result UpdateCategory(Guid categoryId, string name, string description)
    parameters:
    - id: categoryId
      type: System.Guid
    - id: name
      type: System.String
    - id: description
      type: System.String
    return:
      type: Application.Commons.Models.Results.Result
    content.vb: Function UpdateCategory(categoryId As Guid, name As String, description As String) As Result
  overload: Application.Commons.Services.ICategoryService.UpdateCategory*
  nameWithType.vb: ICategoryService.UpdateCategory(Guid, String, String)
  fullName.vb: Application.Commons.Services.ICategoryService.UpdateCategory(System.Guid, String, String)
  name.vb: UpdateCategory(Guid, String, String)
references:
- uid: Application.Commons.Services
  commentId: N:Application.Commons.Services
  href: Application.html
  name: Application.Commons.Services
  nameWithType: Application.Commons.Services
  fullName: Application.Commons.Services
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Services
    name: Services
    href: Application.Commons.Services.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Services
    name: Services
    href: Application.Commons.Services.html
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions.ObjectExtention
  commentId: T:Domain.Extentions.ObjectExtention
  parent: Domain.Extentions
  href: Domain.Extentions.ObjectExtention.html
  name: ObjectExtention
  nameWithType: ObjectExtention
  fullName: Domain.Extentions.ObjectExtention
- uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions
  commentId: N:Domain.Extentions
  href: Domain.html
  name: Domain.Extentions
  nameWithType: Domain.Extentions
  fullName: Domain.Extentions
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
- uid: Application.Commons.Services.ICategoryService.AddCategory*
  commentId: Overload:Application.Commons.Services.ICategoryService.AddCategory
  href: Application.Commons.Services.ICategoryService.html#Application_Commons_Services_ICategoryService_AddCategory_System_String_System_String_System_Nullable_System_Guid__
  name: AddCategory
  nameWithType: ICategoryService.AddCategory
  fullName: Application.Commons.Services.ICategoryService.AddCategory
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Nullable{System.Guid}
  commentId: T:System.Nullable{System.Guid}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid?
  nameWithType: Guid?
  fullName: System.Guid?
  spec.csharp:
  - uid: System.Guid
    name: Guid
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.guid
  - name: '?'
  spec.vb:
  - uid: System.Guid
    name: Guid
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.guid
  - name: '?'
- uid: Application.Commons.Models.Results.Result{Domain.Entities.EntityLookup.Category}
  commentId: T:Application.Commons.Models.Results.Result{Domain.Entities.EntityLookup.Category}
  parent: Application.Commons.Models.Results
  definition: Application.Commons.Models.Results.Result`1
  href: Application.Commons.Models.Results.Result-1.html
  name: Result<Category>
  nameWithType: Result<Category>
  fullName: Application.Commons.Models.Results.Result<Domain.Entities.EntityLookup.Category>
  nameWithType.vb: Result(Of Category)
  fullName.vb: Application.Commons.Models.Results.Result(Of Domain.Entities.EntityLookup.Category)
  name.vb: Result(Of Category)
  spec.csharp:
  - uid: Application.Commons.Models.Results.Result`1
    name: Result
    href: Application.Commons.Models.Results.Result-1.html
  - name: <
  - uid: Domain.Entities.EntityLookup.Category
    name: Category
  - name: '>'
  spec.vb:
  - uid: Application.Commons.Models.Results.Result`1
    name: Result
    href: Application.Commons.Models.Results.Result-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: Domain.Entities.EntityLookup.Category
    name: Category
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Application.Commons.Models.Results.Result`1
  commentId: T:Application.Commons.Models.Results.Result`1
  parent: Application.Commons.Models.Results
  href: Application.Commons.Models.Results.Result-1.html
  name: Result<T>
  nameWithType: Result<T>
  fullName: Application.Commons.Models.Results.Result<T>
  nameWithType.vb: Result(Of T)
  fullName.vb: Application.Commons.Models.Results.Result(Of T)
  name.vb: Result(Of T)
  spec.csharp:
  - uid: Application.Commons.Models.Results.Result`1
    name: Result
    href: Application.Commons.Models.Results.Result-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Application.Commons.Models.Results.Result`1
    name: Result
    href: Application.Commons.Models.Results.Result-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Application.Commons.Models.Results
  commentId: N:Application.Commons.Models.Results
  href: Application.html
  name: Application.Commons.Models.Results
  nameWithType: Application.Commons.Models.Results
  fullName: Application.Commons.Models.Results
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Models
    name: Models
    href: Application.Commons.Models.html
  - name: .
  - uid: Application.Commons.Models.Results
    name: Results
    href: Application.Commons.Models.Results.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Models
    name: Models
    href: Application.Commons.Models.html
  - name: .
  - uid: Application.Commons.Models.Results
    name: Results
    href: Application.Commons.Models.Results.html
- uid: Application.Commons.Services.ICategoryService.UpdateCategory*
  commentId: Overload:Application.Commons.Services.ICategoryService.UpdateCategory
  href: Application.Commons.Services.ICategoryService.html#Application_Commons_Services_ICategoryService_UpdateCategory_System_Guid_System_String_System_String_
  name: UpdateCategory
  nameWithType: ICategoryService.UpdateCategory
  fullName: Application.Commons.Services.ICategoryService.UpdateCategory
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: Application.Commons.Models.Results.Result
  commentId: T:Application.Commons.Models.Results.Result
  parent: Application.Commons.Models.Results
  href: Application.Commons.Models.Results.Result.html
  name: Result
  nameWithType: Result
  fullName: Application.Commons.Models.Results.Result
