### YamlMime:ManagedReference
items:
- uid: Application.Commons.Models.ServicesModel.Source
  commentId: N:Application.Commons.Models.ServicesModel.Source
  id: Application.Commons.Models.ServicesModel.Source
  children:
  - Application.Commons.Models.ServicesModel.Source.AddMetadataSourceModel
  - Application.Commons.Models.ServicesModel.Source.AddSourceReferenceServiceModel
  - Application.Commons.Models.ServicesModel.Source.AddSourceServiceModel
  langs:
  - csharp
  - vb
  name: Application.Commons.Models.ServicesModel.Source
  nameWithType: Application.Commons.Models.ServicesModel.Source
  fullName: Application.Commons.Models.ServicesModel.Source
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Commons.Models.ServicesModel.Source.AddMetadataSourceModel
  commentId: T:Application.Commons.Models.ServicesModel.Source.AddMetadataSourceModel
  href: Application.Commons.Models.ServicesModel.Source.AddMetadataSourceModel.html
  name: AddMetadataSourceModel
  nameWithType: AddMetadataSourceModel
  fullName: Application.Commons.Models.ServicesModel.Source.AddMetadataSourceModel
- uid: Application.Commons.Models.ServicesModel.Source.AddSourceReferenceServiceModel
  commentId: T:Application.Commons.Models.ServicesModel.Source.AddSourceReferenceServiceModel
  href: Application.Commons.Models.ServicesModel.Source.AddSourceReferenceServiceModel.html
  name: AddSourceReferenceServiceModel
  nameWithType: AddSourceReferenceServiceModel
  fullName: Application.Commons.Models.ServicesModel.Source.AddSourceReferenceServiceModel
- uid: Application.Commons.Models.ServicesModel.Source.AddSourceServiceModel
  commentId: T:Application.Commons.Models.ServicesModel.Source.AddSourceServiceModel
  parent: Application.Commons.Models.ServicesModel.Source
  href: Application.Commons.Models.ServicesModel.Source.AddSourceServiceModel.html
  name: AddSourceServiceModel
  nameWithType: AddSourceServiceModel
  fullName: Application.Commons.Models.ServicesModel.Source.AddSourceServiceModel
- uid: Application.Commons.Models.ServicesModel.Source
  commentId: N:Application.Commons.Models.ServicesModel.Source
  href: Application.html
  name: Application.Commons.Models.ServicesModel.Source
  nameWithType: Application.Commons.Models.ServicesModel.Source
  fullName: Application.Commons.Models.ServicesModel.Source
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Models
    name: Models
    href: Application.Commons.Models.html
  - name: .
  - uid: Application.Commons.Models.ServicesModel
    name: ServicesModel
    href: Application.Commons.Models.ServicesModel.html
  - name: .
  - uid: Application.Commons.Models.ServicesModel.Source
    name: Source
    href: Application.Commons.Models.ServicesModel.Source.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Models
    name: Models
    href: Application.Commons.Models.html
  - name: .
  - uid: Application.Commons.Models.ServicesModel
    name: ServicesModel
    href: Application.Commons.Models.ServicesModel.html
  - name: .
  - uid: Application.Commons.Models.ServicesModel.Source
    name: Source
    href: Application.Commons.Models.ServicesModel.Source.html
