### YamlMime:ManagedReference
items:
- uid: Application.Tags.Commands.AddTag.AddTagCommand
  commentId: T:Application.Tags.Commands.AddTag.AddTagCommand
  id: AddTagCommand
  parent: Application.Tags.Commands.AddTag
  children:
  - Application.Tags.Commands.AddTag.AddTagCommand.BackgroundColorCode
  - Application.Tags.Commands.AddTag.AddTagCommand.Name
  - Application.Tags.Commands.AddTag.AddTagCommand.TextColorCode
  langs:
  - csharp
  - vb
  name: AddTagCommand
  nameWithType: AddTagCommand
  fullName: Application.Tags.Commands.AddTag.AddTagCommand
  type: Class
  source:
    remote:
      path: src/Application/Tags/Commands/AddTag/AddTagCommand.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: AddTagCommand
    path: src/Application/Tags/Commands/AddTag/AddTagCommand.cs
    startLine: 7
  assemblies:
  - Application
  namespace: Application.Tags.Commands.AddTag
  syntax:
    content: >-
      [SwaggerSchema(null, Description = "a command for creating a new tag", Nullable = false, Required = new string[] { "name" })]

      public class AddTagCommand : IRequest<Result<AddTagCommandResult>>, IBaseRequest
    content.vb: >-
      <SwaggerSchema(Nothing, Description:="a command for creating a new tag", Nullable:=False, Required:=New String() { "name" })>

      Public Class AddTagCommand Implements IRequest(Of Result(Of AddTagCommandResult)), IBaseRequest
  inheritance:
  - System.Object
  implements:
  - MediatR.IRequest{Application.Commons.Models.Results.Result{Application.Tags.Commands.AddTag.AddTagCommandResult}}
  - MediatR.IBaseRequest
  extensionMethods:
  - System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  - System.Object.Domain.Extentions.ObjectExtention.IsNull
  attributes:
  - type: Swashbuckle.AspNetCore.Annotations.SwaggerSchemaAttribute
    ctor: Swashbuckle.AspNetCore.Annotations.SwaggerSchemaAttribute.#ctor(System.String)
    arguments:
    - type: System.String
    namedArguments:
    - name: Description
      type: System.String
      value: a command for creating a new tag
    - name: Nullable
      type: System.Boolean
      value: false
- uid: Application.Tags.Commands.AddTag.AddTagCommand.Name
  commentId: P:Application.Tags.Commands.AddTag.AddTagCommand.Name
  id: Name
  parent: Application.Tags.Commands.AddTag.AddTagCommand
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: AddTagCommand.Name
  fullName: Application.Tags.Commands.AddTag.AddTagCommand.Name
  type: Property
  source:
    remote:
      path: src/Application/Tags/Commands/AddTag/AddTagCommand.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Name
    path: src/Application/Tags/Commands/AddTag/AddTagCommand.cs
    startLine: 10
  assemblies:
  - Application
  namespace: Application.Tags.Commands.AddTag
  syntax:
    content: >-
      [SwaggerSchema(null, Description = "the Value for tag", Nullable = false, Title = "Tag Color")]

      [SwaggerExample("Math-101")]

      public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <SwaggerSchema(Nothing, Description:="the Value for tag", Nullable:=False, Title:="Tag Color")>

      <SwaggerExample("Math-101")>

      Public Property Name As String
  overload: Application.Tags.Commands.AddTag.AddTagCommand.Name*
  attributes:
  - type: Swashbuckle.AspNetCore.Annotations.SwaggerSchemaAttribute
    ctor: Swashbuckle.AspNetCore.Annotations.SwaggerSchemaAttribute.#ctor(System.String)
    arguments:
    - type: System.String
    namedArguments:
    - name: Description
      type: System.String
      value: the Value for tag
    - name: Nullable
      type: System.Boolean
      value: false
    - name: Title
      type: System.String
      value: Tag Color
  - type: Application.Commons.Attributes.SwaggerExampleAttribute
    ctor: Application.Commons.Attributes.SwaggerExampleAttribute.#ctor(System.Object)
    arguments:
    - type: System.String
      value: Math-101
- uid: Application.Tags.Commands.AddTag.AddTagCommand.BackgroundColorCode
  commentId: P:Application.Tags.Commands.AddTag.AddTagCommand.BackgroundColorCode
  id: BackgroundColorCode
  parent: Application.Tags.Commands.AddTag.AddTagCommand
  langs:
  - csharp
  - vb
  name: BackgroundColorCode
  nameWithType: AddTagCommand.BackgroundColorCode
  fullName: Application.Tags.Commands.AddTag.AddTagCommand.BackgroundColorCode
  type: Property
  source:
    remote:
      path: src/Application/Tags/Commands/AddTag/AddTagCommand.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: BackgroundColorCode
    path: src/Application/Tags/Commands/AddTag/AddTagCommand.cs
    startLine: 13
  assemblies:
  - Application
  namespace: Application.Tags.Commands.AddTag
  syntax:
    content: >-
      [SwaggerSchema(null, Description = "Hexcode color format should start with #", Nullable = true, Title = "Tag Color")]

      [SwaggerExample("#1756a7")]

      public string? BackgroundColorCode { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <SwaggerSchema(Nothing, Description:="Hexcode color format should start with #", Nullable:=True, Title:="Tag Color")>

      <SwaggerExample("#1756a7")>

      Public Property BackgroundColorCode As String
  overload: Application.Tags.Commands.AddTag.AddTagCommand.BackgroundColorCode*
  attributes:
  - type: Swashbuckle.AspNetCore.Annotations.SwaggerSchemaAttribute
    ctor: Swashbuckle.AspNetCore.Annotations.SwaggerSchemaAttribute.#ctor(System.String)
    arguments:
    - type: System.String
    namedArguments:
    - name: Description
      type: System.String
      value: 'Hexcode color format should start with #'
    - name: Nullable
      type: System.Boolean
      value: true
    - name: Title
      type: System.String
      value: Tag Color
  - type: Application.Commons.Attributes.SwaggerExampleAttribute
    ctor: Application.Commons.Attributes.SwaggerExampleAttribute.#ctor(System.Object)
    arguments:
    - type: System.String
      value: '#1756a7'
- uid: Application.Tags.Commands.AddTag.AddTagCommand.TextColorCode
  commentId: P:Application.Tags.Commands.AddTag.AddTagCommand.TextColorCode
  id: TextColorCode
  parent: Application.Tags.Commands.AddTag.AddTagCommand
  langs:
  - csharp
  - vb
  name: TextColorCode
  nameWithType: AddTagCommand.TextColorCode
  fullName: Application.Tags.Commands.AddTag.AddTagCommand.TextColorCode
  type: Property
  source:
    remote:
      path: src/Application/Tags/Commands/AddTag/AddTagCommand.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: TextColorCode
    path: src/Application/Tags/Commands/AddTag/AddTagCommand.cs
    startLine: 16
  assemblies:
  - Application
  namespace: Application.Tags.Commands.AddTag
  syntax:
    content: >-
      [SwaggerSchema(null, Description = "Hexcode color format should start with #", Nullable = true, Title = "Tag Color")]

      [SwaggerExample("#1756a7")]

      public string? TextColorCode { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <SwaggerSchema(Nothing, Description:="Hexcode color format should start with #", Nullable:=True, Title:="Tag Color")>

      <SwaggerExample("#1756a7")>

      Public Property TextColorCode As String
  overload: Application.Tags.Commands.AddTag.AddTagCommand.TextColorCode*
  attributes:
  - type: Swashbuckle.AspNetCore.Annotations.SwaggerSchemaAttribute
    ctor: Swashbuckle.AspNetCore.Annotations.SwaggerSchemaAttribute.#ctor(System.String)
    arguments:
    - type: System.String
    namedArguments:
    - name: Description
      type: System.String
      value: 'Hexcode color format should start with #'
    - name: Nullable
      type: System.Boolean
      value: true
    - name: Title
      type: System.String
      value: Tag Color
  - type: Application.Commons.Attributes.SwaggerExampleAttribute
    ctor: Application.Commons.Attributes.SwaggerExampleAttribute.#ctor(System.Object)
    arguments:
    - type: System.String
      value: '#1756a7'
references:
- uid: Application.Tags.Commands.AddTag
  commentId: N:Application.Tags.Commands.AddTag
  href: Application.html
  name: Application.Tags.Commands.AddTag
  nameWithType: Application.Tags.Commands.AddTag
  fullName: Application.Tags.Commands.AddTag
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Tags
    name: Tags
    href: Application.Tags.html
  - name: .
  - uid: Application.Tags.Commands
    name: Commands
    href: Application.Tags.Commands.html
  - name: .
  - uid: Application.Tags.Commands.AddTag
    name: AddTag
    href: Application.Tags.Commands.AddTag.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Tags
    name: Tags
    href: Application.Tags.html
  - name: .
  - uid: Application.Tags.Commands
    name: Commands
    href: Application.Tags.Commands.html
  - name: .
  - uid: Application.Tags.Commands.AddTag
    name: AddTag
    href: Application.Tags.Commands.AddTag.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MediatR.IRequest{Application.Commons.Models.Results.Result{Application.Tags.Commands.AddTag.AddTagCommandResult}}
  commentId: T:MediatR.IRequest{Application.Commons.Models.Results.Result{Application.Tags.Commands.AddTag.AddTagCommandResult}}
  parent: MediatR
  definition: MediatR.IRequest`1
  href: Application.Commons.Models.Results.Result-1.html
  name: IRequest<Result<AddTagCommandResult>>
  nameWithType: IRequest<Result<AddTagCommandResult>>
  fullName: MediatR.IRequest<Application.Commons.Models.Results.Result<Application.Tags.Commands.AddTag.AddTagCommandResult>>
  nameWithType.vb: IRequest(Of Result(Of AddTagCommandResult))
  fullName.vb: MediatR.IRequest(Of Application.Commons.Models.Results.Result(Of Application.Tags.Commands.AddTag.AddTagCommandResult))
  name.vb: IRequest(Of Result(Of AddTagCommandResult))
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - uid: Application.Commons.Models.Results.Result`1
    name: Result
    href: Application.Commons.Models.Results.Result-1.html
  - name: <
  - uid: Application.Tags.Commands.AddTag.AddTagCommandResult
    name: AddTagCommandResult
    href: Application.Tags.Commands.AddTag.AddTagCommandResult.html
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Application.Commons.Models.Results.Result`1
    name: Result
    href: Application.Commons.Models.Results.Result-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: Application.Tags.Commands.AddTag.AddTagCommandResult
    name: AddTagCommandResult
    href: Application.Tags.Commands.AddTag.AddTagCommandResult.html
  - name: )
  - name: )
- uid: MediatR.IBaseRequest
  commentId: T:MediatR.IBaseRequest
  parent: MediatR
  isExternal: true
  name: IBaseRequest
  nameWithType: IBaseRequest
  fullName: MediatR.IBaseRequest
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MediatR.IRequest`1
  commentId: T:MediatR.IRequest`1
  isExternal: true
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: MediatR.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: MediatR.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: MediatR
  commentId: N:MediatR
  isExternal: true
  name: MediatR
  nameWithType: MediatR
  fullName: MediatR
- uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions.ObjectExtention
  commentId: T:Domain.Extentions.ObjectExtention
  parent: Domain.Extentions
  href: Domain.Extentions.ObjectExtention.html
  name: ObjectExtention
  nameWithType: ObjectExtention
  fullName: Domain.Extentions.ObjectExtention
- uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions
  commentId: N:Domain.Extentions
  href: Domain.html
  name: Domain.Extentions
  nameWithType: Domain.Extentions
  fullName: Domain.Extentions
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
- uid: Application.Tags.Commands.AddTag.AddTagCommand.Name*
  commentId: Overload:Application.Tags.Commands.AddTag.AddTagCommand.Name
  href: Application.Tags.Commands.AddTag.AddTagCommand.html#Application_Tags_Commands_AddTag_AddTagCommand_Name
  name: Name
  nameWithType: AddTagCommand.Name
  fullName: Application.Tags.Commands.AddTag.AddTagCommand.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Application.Tags.Commands.AddTag.AddTagCommand.BackgroundColorCode*
  commentId: Overload:Application.Tags.Commands.AddTag.AddTagCommand.BackgroundColorCode
  href: Application.Tags.Commands.AddTag.AddTagCommand.html#Application_Tags_Commands_AddTag_AddTagCommand_BackgroundColorCode
  name: BackgroundColorCode
  nameWithType: AddTagCommand.BackgroundColorCode
  fullName: Application.Tags.Commands.AddTag.AddTagCommand.BackgroundColorCode
- uid: Application.Tags.Commands.AddTag.AddTagCommand.TextColorCode*
  commentId: Overload:Application.Tags.Commands.AddTag.AddTagCommand.TextColorCode
  href: Application.Tags.Commands.AddTag.AddTagCommand.html#Application_Tags_Commands_AddTag_AddTagCommand_TextColorCode
  name: TextColorCode
  nameWithType: AddTagCommand.TextColorCode
  fullName: Application.Tags.Commands.AddTag.AddTagCommand.TextColorCode
