### YamlMime:ManagedReference
items:
- uid: Application.EntitlesTimeline.Queries.EntityTimeline
  commentId: N:Application.EntitlesTimeline.Queries.EntityTimeline
  id: Application.EntitlesTimeline.Queries.EntityTimeline
  children:
  - Application.EntitlesTimeline.Queries.EntityTimeline.GetEntityTimelineQuery
  langs:
  - csharp
  - vb
  name: Application.EntitlesTimeline.Queries.EntityTimeline
  nameWithType: Application.EntitlesTimeline.Queries.EntityTimeline
  fullName: Application.EntitlesTimeline.Queries.EntityTimeline
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.EntitlesTimeline.Queries.EntityTimeline.GetEntityTimelineQuery
  commentId: T:Application.EntitlesTimeline.Queries.EntityTimeline.GetEntityTimelineQuery
  parent: Application.EntitlesTimeline.Queries.EntityTimeline
  href: Application.EntitlesTimeline.Queries.EntityTimeline.GetEntityTimelineQuery.html
  name: GetEntityTimelineQuery
  nameWithType: GetEntityTimelineQuery
  fullName: Application.EntitlesTimeline.Queries.EntityTimeline.GetEntityTimelineQuery
- uid: Application.EntitlesTimeline.Queries.EntityTimeline
  commentId: N:Application.EntitlesTimeline.Queries.EntityTimeline
  href: Application.html
  name: Application.EntitlesTimeline.Queries.EntityTimeline
  nameWithType: Application.EntitlesTimeline.Queries.EntityTimeline
  fullName: Application.EntitlesTimeline.Queries.EntityTimeline
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.EntitlesTimeline
    name: EntitlesTimeline
    href: Application.EntitlesTimeline.html
  - name: .
  - uid: Application.EntitlesTimeline.Queries
    name: Queries
    href: Application.EntitlesTimeline.Queries.html
  - name: .
  - uid: Application.EntitlesTimeline.Queries.EntityTimeline
    name: EntityTimeline
    href: Application.EntitlesTimeline.Queries.EntityTimeline.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.EntitlesTimeline
    name: EntitlesTimeline
    href: Application.EntitlesTimeline.html
  - name: .
  - uid: Application.EntitlesTimeline.Queries
    name: Queries
    href: Application.EntitlesTimeline.Queries.html
  - name: .
  - uid: Application.EntitlesTimeline.Queries.EntityTimeline
    name: EntityTimeline
    href: Application.EntitlesTimeline.Queries.EntityTimeline.html
