### YamlMime:ManagedReference
items:
- uid: Application.Categories.Queries.GetCategoryById
  commentId: N:Application.Categories.Queries.GetCategoryById
  id: Application.Categories.Queries.GetCategoryById
  children:
  - Application.Categories.Queries.GetCategoryById.GetCategoryByIdQuery
  - Application.Categories.Queries.GetCategoryById.GetCategoryByIdQueryHandler
  - Application.Categories.Queries.GetCategoryById.GetCategoryByIdQueryResult
  langs:
  - csharp
  - vb
  name: Application.Categories.Queries.GetCategoryById
  nameWithType: Application.Categories.Queries.GetCategoryById
  fullName: Application.Categories.Queries.GetCategoryById
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Categories.Queries.GetCategoryById.GetCategoryByIdQuery
  commentId: T:Application.Categories.Queries.GetCategoryById.GetCategoryByIdQuery
  parent: Application.Categories.Queries.GetCategoryById
  href: Application.Categories.Queries.GetCategoryById.GetCategoryByIdQuery.html
  name: GetCategoryByIdQuery
  nameWithType: GetCategoryByIdQuery
  fullName: Application.Categories.Queries.GetCategoryById.GetCategoryByIdQuery
- uid: Application.Categories.Queries.GetCategoryById.GetCategoryByIdQueryHandler
  commentId: T:Application.Categories.Queries.GetCategoryById.GetCategoryByIdQueryHandler
  href: Application.Categories.Queries.GetCategoryById.GetCategoryByIdQueryHandler.html
  name: GetCategoryByIdQueryHandler
  nameWithType: GetCategoryByIdQueryHandler
  fullName: Application.Categories.Queries.GetCategoryById.GetCategoryByIdQueryHandler
- uid: Application.Categories.Queries.GetCategoryById.GetCategoryByIdQueryResult
  commentId: T:Application.Categories.Queries.GetCategoryById.GetCategoryByIdQueryResult
  href: Application.Categories.Queries.GetCategoryById.GetCategoryByIdQueryResult.html
  name: GetCategoryByIdQueryResult
  nameWithType: GetCategoryByIdQueryResult
  fullName: Application.Categories.Queries.GetCategoryById.GetCategoryByIdQueryResult
- uid: Application.Categories.Queries.GetCategoryById
  commentId: N:Application.Categories.Queries.GetCategoryById
  href: Application.html
  name: Application.Categories.Queries.GetCategoryById
  nameWithType: Application.Categories.Queries.GetCategoryById
  fullName: Application.Categories.Queries.GetCategoryById
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Categories
    name: Categories
    href: Application.Categories.html
  - name: .
  - uid: Application.Categories.Queries
    name: Queries
    href: Application.Categories.Queries.html
  - name: .
  - uid: Application.Categories.Queries.GetCategoryById
    name: GetCategoryById
    href: Application.Categories.Queries.GetCategoryById.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Categories
    name: Categories
    href: Application.Categories.html
  - name: .
  - uid: Application.Categories.Queries
    name: Queries
    href: Application.Categories.Queries.html
  - name: .
  - uid: Application.Categories.Queries.GetCategoryById
    name: GetCategoryById
    href: Application.Categories.Queries.GetCategoryById.html
