### YamlMime:ManagedReference
items:
- uid: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult
  commentId: T:Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult
  id: GetLanguagesQueryResult
  parent: Application.Lookups.Queries.Languages.GetLanguages
  children:
  - Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Code
  - Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.DisplayName
  - Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Id
  langs:
  - csharp
  - vb
  name: GetLanguagesQueryResult
  nameWithType: GetLanguagesQueryResult
  fullName: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult
  type: Class
  source:
    remote:
      path: src/Application/Lookups/Queries/Languages/GetLanguages/GetLanguagesQueryResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: GetLanguagesQueryResult
    path: src/Application/Lookups/Queries/Languages/GetLanguages/GetLanguagesQueryResult.cs
    startLine: 4
  assemblies:
  - Application
  namespace: Application.Lookups.Queries.Languages.GetLanguages
  syntax:
    content: public class GetLanguagesQueryResult
    content.vb: Public Class GetLanguagesQueryResult
  inheritance:
  - System.Object
  extensionMethods:
  - System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  - System.Object.Domain.Extentions.ObjectExtention.IsNull
- uid: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Id
  commentId: P:Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Id
  id: Id
  parent: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: GetLanguagesQueryResult.Id
  fullName: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Id
  type: Property
  source:
    remote:
      path: src/Application/Lookups/Queries/Languages/GetLanguages/GetLanguagesQueryResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Id
    path: src/Application/Lookups/Queries/Languages/GetLanguages/GetLanguagesQueryResult.cs
    startLine: 6
  assemblies:
  - Application
  namespace: Application.Lookups.Queries.Languages.GetLanguages
  syntax:
    content: public Guid Id { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property Id As Guid
  overload: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Id*
- uid: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Code
  commentId: P:Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Code
  id: Code
  parent: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult
  langs:
  - csharp
  - vb
  name: Code
  nameWithType: GetLanguagesQueryResult.Code
  fullName: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Code
  type: Property
  source:
    remote:
      path: src/Application/Lookups/Queries/Languages/GetLanguages/GetLanguagesQueryResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Code
    path: src/Application/Lookups/Queries/Languages/GetLanguages/GetLanguagesQueryResult.cs
    startLine: 7
  assemblies:
  - Application
  namespace: Application.Lookups.Queries.Languages.GetLanguages
  syntax:
    content: public required string Code { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Code As String
  overload: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Code*
- uid: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.DisplayName
  commentId: P:Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.DisplayName
  id: DisplayName
  parent: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult
  langs:
  - csharp
  - vb
  name: DisplayName
  nameWithType: GetLanguagesQueryResult.DisplayName
  fullName: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.DisplayName
  type: Property
  source:
    remote:
      path: src/Application/Lookups/Queries/Languages/GetLanguages/GetLanguagesQueryResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: DisplayName
    path: src/Application/Lookups/Queries/Languages/GetLanguages/GetLanguagesQueryResult.cs
    startLine: 8
  assemblies:
  - Application
  namespace: Application.Lookups.Queries.Languages.GetLanguages
  syntax:
    content: public required string DisplayName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property DisplayName As String
  overload: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.DisplayName*
references:
- uid: Application.Lookups.Queries.Languages.GetLanguages
  commentId: N:Application.Lookups.Queries.Languages.GetLanguages
  href: Application.html
  name: Application.Lookups.Queries.Languages.GetLanguages
  nameWithType: Application.Lookups.Queries.Languages.GetLanguages
  fullName: Application.Lookups.Queries.Languages.GetLanguages
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Lookups
    name: Lookups
    href: Application.Lookups.html
  - name: .
  - uid: Application.Lookups.Queries
    name: Queries
    href: Application.Lookups.Queries.html
  - name: .
  - uid: Application.Lookups.Queries.Languages
    name: Languages
    href: Application.Lookups.Queries.Languages.html
  - name: .
  - uid: Application.Lookups.Queries.Languages.GetLanguages
    name: GetLanguages
    href: Application.Lookups.Queries.Languages.GetLanguages.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Lookups
    name: Lookups
    href: Application.Lookups.html
  - name: .
  - uid: Application.Lookups.Queries
    name: Queries
    href: Application.Lookups.Queries.html
  - name: .
  - uid: Application.Lookups.Queries.Languages
    name: Languages
    href: Application.Lookups.Queries.Languages.html
  - name: .
  - uid: Application.Lookups.Queries.Languages.GetLanguages
    name: GetLanguages
    href: Application.Lookups.Queries.Languages.GetLanguages.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions.ObjectExtention
  commentId: T:Domain.Extentions.ObjectExtention
  parent: Domain.Extentions
  href: Domain.Extentions.ObjectExtention.html
  name: ObjectExtention
  nameWithType: ObjectExtention
  fullName: Domain.Extentions.ObjectExtention
- uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions
  commentId: N:Domain.Extentions
  href: Domain.html
  name: Domain.Extentions
  nameWithType: Domain.Extentions
  fullName: Domain.Extentions
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
- uid: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Id*
  commentId: Overload:Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Id
  href: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.html#Application_Lookups_Queries_Languages_GetLanguages_GetLanguagesQueryResult_Id
  name: Id
  nameWithType: GetLanguagesQueryResult.Id
  fullName: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Id
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Code*
  commentId: Overload:Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Code
  href: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.html#Application_Lookups_Queries_Languages_GetLanguages_GetLanguagesQueryResult_Code
  name: Code
  nameWithType: GetLanguagesQueryResult.Code
  fullName: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.Code
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.DisplayName*
  commentId: Overload:Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.DisplayName
  href: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.html#Application_Lookups_Queries_Languages_GetLanguages_GetLanguagesQueryResult_DisplayName
  name: DisplayName
  nameWithType: GetLanguagesQueryResult.DisplayName
  fullName: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.DisplayName
