### YamlMime:ManagedReference
items:
- uid: Application.Commons.Managers
  commentId: N:Application.Commons.Managers
  id: Application.Commons.Managers
  children:
  - Application.Commons.Managers.IAuditManager
  - Application.Commons.Managers.IServiceManager
  - Application.Commons.Managers.ISystemManager
  langs:
  - csharp
  - vb
  name: Application.Commons.Managers
  nameWithType: Application.Commons.Managers
  fullName: Application.Commons.Managers
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Commons.Managers.IAuditManager
  commentId: T:Application.Commons.Managers.IAuditManager
  parent: Application.Commons.Managers
  href: Application.Commons.Managers.IAuditManager.html
  name: IAuditManager
  nameWithType: IAuditManager
  fullName: Application.Commons.Managers.IAuditManager
- uid: Application.Commons.Managers.IServiceManager
  commentId: T:Application.Commons.Managers.IServiceManager
  parent: Application.Commons.Managers
  href: Application.Commons.Managers.IServiceManager.html
  name: IServiceManager
  nameWithType: IServiceManager
  fullName: Application.Commons.Managers.IServiceManager
- uid: Application.Commons.Managers.ISystemManager
  commentId: T:Application.Commons.Managers.ISystemManager
  parent: Application.Commons.Managers
  href: Application.Commons.Managers.ISystemManager.html
  name: ISystemManager
  nameWithType: ISystemManager
  fullName: Application.Commons.Managers.ISystemManager
- uid: Application.Commons.Managers
  commentId: N:Application.Commons.Managers
  href: Application.html
  name: Application.Commons.Managers
  nameWithType: Application.Commons.Managers
  fullName: Application.Commons.Managers
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Managers
    name: Managers
    href: Application.Commons.Managers.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Managers
    name: Managers
    href: Application.Commons.Managers.html
