### YamlMime:ManagedReference
items:
- uid: Application.Questions.Commands.UpdateQuestion
  commentId: N:Application.Questions.Commands.UpdateQuestion
  id: Application.Questions.Commands.UpdateQuestion
  children:
  - Application.Questions.Commands.UpdateQuestion.UpdateQuestionCommand
  - Application.Questions.Commands.UpdateQuestion.UpdateQuestionCommandHandler
  langs:
  - csharp
  - vb
  name: Application.Questions.Commands.UpdateQuestion
  nameWithType: Application.Questions.Commands.UpdateQuestion
  fullName: Application.Questions.Commands.UpdateQuestion
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Questions.Commands.UpdateQuestion.UpdateQuestionCommand
  commentId: T:Application.Questions.Commands.UpdateQuestion.UpdateQuestionCommand
  parent: Application.Questions.Commands.UpdateQuestion
  href: Application.Questions.Commands.UpdateQuestion.UpdateQuestionCommand.html
  name: UpdateQuestionCommand
  nameWithType: UpdateQuestionCommand
  fullName: Application.Questions.Commands.UpdateQuestion.UpdateQuestionCommand
- uid: Application.Questions.Commands.UpdateQuestion.UpdateQuestionCommandHandler
  commentId: T:Application.Questions.Commands.UpdateQuestion.UpdateQuestionCommandHandler
  href: Application.Questions.Commands.UpdateQuestion.UpdateQuestionCommandHandler.html
  name: UpdateQuestionCommandHandler
  nameWithType: UpdateQuestionCommandHandler
  fullName: Application.Questions.Commands.UpdateQuestion.UpdateQuestionCommandHandler
- uid: Application.Questions.Commands.UpdateQuestion
  commentId: N:Application.Questions.Commands.UpdateQuestion
  href: Application.html
  name: Application.Questions.Commands.UpdateQuestion
  nameWithType: Application.Questions.Commands.UpdateQuestion
  fullName: Application.Questions.Commands.UpdateQuestion
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Questions
    name: Questions
    href: Application.Questions.html
  - name: .
  - uid: Application.Questions.Commands
    name: Commands
    href: Application.Questions.Commands.html
  - name: .
  - uid: Application.Questions.Commands.UpdateQuestion
    name: UpdateQuestion
    href: Application.Questions.Commands.UpdateQuestion.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Questions
    name: Questions
    href: Application.Questions.html
  - name: .
  - uid: Application.Questions.Commands
    name: Commands
    href: Application.Questions.Commands.html
  - name: .
  - uid: Application.Questions.Commands.UpdateQuestion
    name: UpdateQuestion
    href: Application.Questions.Commands.UpdateQuestion.html
