### YamlMime:ManagedReference
items:
- uid: Application.Commons.MappingConfig.SourceMapper
  commentId: T:Application.Commons.MappingConfig.SourceMapper
  id: SourceMapper
  parent: Application.Commons.MappingConfig
  children:
  - Application.Commons.MappingConfig.SourceMapper.Register(Mapster.TypeAdapterConfig)
  langs:
  - csharp
  - vb
  name: SourceMapper
  nameWithType: SourceMapper
  fullName: Application.Commons.MappingConfig.SourceMapper
  type: Class
  source:
    remote:
      path: src/Application/Commons/MappingConfig/SourceMapper.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: SourceMapper
    path: src/Application/Commons/MappingConfig/SourceMapper.cs
    startLine: 10
  assemblies:
  - Application
  namespace: Application.Commons.MappingConfig
  syntax:
    content: 'public class SourceMapper : IRegister'
    content.vb: Public Class SourceMapper Implements IRegister
  inheritance:
  - System.Object
  implements:
  - Mapster.IRegister
  extensionMethods:
  - System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  - System.Object.Domain.Extentions.ObjectExtention.IsNull
- uid: Application.Commons.MappingConfig.SourceMapper.Register(Mapster.TypeAdapterConfig)
  commentId: M:Application.Commons.MappingConfig.SourceMapper.Register(Mapster.TypeAdapterConfig)
  id: Register(Mapster.TypeAdapterConfig)
  parent: Application.Commons.MappingConfig.SourceMapper
  langs:
  - csharp
  - vb
  name: Register(TypeAdapterConfig)
  nameWithType: SourceMapper.Register(TypeAdapterConfig)
  fullName: Application.Commons.MappingConfig.SourceMapper.Register(Mapster.TypeAdapterConfig)
  type: Method
  source:
    remote:
      path: src/Application/Commons/MappingConfig/SourceMapper.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Register
    path: src/Application/Commons/MappingConfig/SourceMapper.cs
    startLine: 12
  assemblies:
  - Application
  namespace: Application.Commons.MappingConfig
  example: []
  syntax:
    content: public void Register(TypeAdapterConfig config)
    parameters:
    - id: config
      type: Mapster.TypeAdapterConfig
    content.vb: Public Sub Register(config As TypeAdapterConfig)
  overload: Application.Commons.MappingConfig.SourceMapper.Register*
  implements:
  - Mapster.IRegister.Register(Mapster.TypeAdapterConfig)
references:
- uid: Application.Commons.MappingConfig
  commentId: N:Application.Commons.MappingConfig
  href: Application.html
  name: Application.Commons.MappingConfig
  nameWithType: Application.Commons.MappingConfig
  fullName: Application.Commons.MappingConfig
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.MappingConfig
    name: MappingConfig
    href: Application.Commons.MappingConfig.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.MappingConfig
    name: MappingConfig
    href: Application.Commons.MappingConfig.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Mapster.IRegister
  commentId: T:Mapster.IRegister
  parent: Mapster
  isExternal: true
  name: IRegister
  nameWithType: IRegister
  fullName: Mapster.IRegister
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Mapster
  commentId: N:Mapster
  isExternal: true
  name: Mapster
  nameWithType: Mapster
  fullName: Mapster
- uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions.ObjectExtention
  commentId: T:Domain.Extentions.ObjectExtention
  parent: Domain.Extentions
  href: Domain.Extentions.ObjectExtention.html
  name: ObjectExtention
  nameWithType: ObjectExtention
  fullName: Domain.Extentions.ObjectExtention
- uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions
  commentId: N:Domain.Extentions
  href: Domain.html
  name: Domain.Extentions
  nameWithType: Domain.Extentions
  fullName: Domain.Extentions
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
- uid: Application.Commons.MappingConfig.SourceMapper.Register*
  commentId: Overload:Application.Commons.MappingConfig.SourceMapper.Register
  href: Application.Commons.MappingConfig.SourceMapper.html#Application_Commons_MappingConfig_SourceMapper_Register_Mapster_TypeAdapterConfig_
  name: Register
  nameWithType: SourceMapper.Register
  fullName: Application.Commons.MappingConfig.SourceMapper.Register
- uid: Mapster.IRegister.Register(Mapster.TypeAdapterConfig)
  commentId: M:Mapster.IRegister.Register(Mapster.TypeAdapterConfig)
  parent: Mapster.IRegister
  isExternal: true
  name: Register(TypeAdapterConfig)
  nameWithType: IRegister.Register(TypeAdapterConfig)
  fullName: Mapster.IRegister.Register(Mapster.TypeAdapterConfig)
  spec.csharp:
  - uid: Mapster.IRegister.Register(Mapster.TypeAdapterConfig)
    name: Register
    isExternal: true
  - name: (
  - uid: Mapster.TypeAdapterConfig
    name: TypeAdapterConfig
    isExternal: true
  - name: )
  spec.vb:
  - uid: Mapster.IRegister.Register(Mapster.TypeAdapterConfig)
    name: Register
    isExternal: true
  - name: (
  - uid: Mapster.TypeAdapterConfig
    name: TypeAdapterConfig
    isExternal: true
  - name: )
- uid: Mapster.TypeAdapterConfig
  commentId: T:Mapster.TypeAdapterConfig
  parent: Mapster
  isExternal: true
  name: TypeAdapterConfig
  nameWithType: TypeAdapterConfig
  fullName: Mapster.TypeAdapterConfig
