### YamlMime:ManagedReference
items:
- uid: Application.Commons.SharedModelResult.Source
  commentId: N:Application.Commons.SharedModelResult.Source
  id: Application.Commons.SharedModelResult.Source
  children:
  - Application.Commons.SharedModelResult.Source.MetadataResult
  - Application.Commons.SharedModelResult.Source.SourceResult
  langs:
  - csharp
  - vb
  name: Application.Commons.SharedModelResult.Source
  nameWithType: Application.Commons.SharedModelResult.Source
  fullName: Application.Commons.SharedModelResult.Source
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Commons.SharedModelResult.Source.MetadataResult
  commentId: T:Application.Commons.SharedModelResult.Source.MetadataResult
  href: Application.Commons.SharedModelResult.Source.MetadataResult.html
  name: MetadataResult
  nameWithType: MetadataResult
  fullName: Application.Commons.SharedModelResult.Source.MetadataResult
- uid: Application.Commons.SharedModelResult.Source.SourceResult
  commentId: T:Application.Commons.SharedModelResult.Source.SourceResult
  href: Application.Commons.SharedModelResult.Source.SourceResult.html
  name: SourceResult
  nameWithType: SourceResult
  fullName: Application.Commons.SharedModelResult.Source.SourceResult
