### YamlMime:ManagedReference
items:
- uid: Application.Commons.Extensions
  commentId: N:Application.Commons.Extensions
  id: Application.Commons.Extensions
  children:
  - Application.Commons.Extensions.CloneExtension
  - Application.Commons.Extensions.LoggingLevelController
  - Application.Commons.Extensions.StringExtension
  langs:
  - csharp
  - vb
  name: Application.Commons.Extensions
  nameWithType: Application.Commons.Extensions
  fullName: Application.Commons.Extensions
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Commons.Extensions.CloneExtension
  commentId: T:Application.Commons.Extensions.CloneExtension
  href: Application.Commons.Extensions.CloneExtension.html
  name: CloneExtension
  nameWithType: CloneExtension
  fullName: Application.Commons.Extensions.CloneExtension
- uid: Application.Commons.Extensions.LoggingLevelController
  commentId: T:Application.Commons.Extensions.LoggingLevelController
  href: Application.Commons.Extensions.LoggingLevelController.html
  name: LoggingLevelController
  nameWithType: LoggingLevelController
  fullName: Application.Commons.Extensions.LoggingLevelController
- uid: Application.Commons.Extensions.StringExtension
  commentId: T:Application.Commons.Extensions.StringExtension
  href: Application.Commons.Extensions.StringExtension.html
  name: StringExtension
  nameWithType: StringExtension
  fullName: Application.Commons.Extensions.StringExtension
