### YamlMime:ManagedReference
items:
- uid: Application.Commons.Extentions
  commentId: N:Application.Commons.Extentions
  id: Application.Commons.Extentions
  children:
  - Application.Commons.Extentions.QuestionDifficultyExtenstion
  langs:
  - csharp
  - vb
  name: Application.Commons.Extentions
  nameWithType: Application.Commons.Extentions
  fullName: Application.Commons.Extentions
  type: Namespace
  assemblies:
  - Domain
references:
- uid: Application.Commons.Extentions.QuestionDifficultyExtenstion
  commentId: T:Application.Commons.Extentions.QuestionDifficultyExtenstion
  parent: Application.Commons.Extentions
  href: Application.Commons.Extentions.QuestionDifficultyExtenstion.html
  name: QuestionDifficultyExtenstion
  nameWithType: QuestionDifficultyExtenstion
  fullName: Application.Commons.Extentions.QuestionDifficultyExtenstion
- uid: Application.Commons.Extentions
  commentId: N:Application.Commons.Extentions
  href: Application.html
  name: Application.Commons.Extentions
  nameWithType: Application.Commons.Extentions
  fullName: Application.Commons.Extentions
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Extentions
    name: Extentions
    href: Application.Commons.Extentions.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Extentions
    name: Extentions
    href: Application.Commons.Extentions.html
