### YamlMime:ManagedReference
items:
- uid: Application.Questions.Commands.UpdateQuestion.Models
  commentId: N:Application.Questions.Commands.UpdateQuestion.Models
  id: Application.Questions.Commands.UpdateQuestion.Models
  children:
  - Application.Questions.Commands.UpdateQuestion.Models.QuestionSourceUpdateCommand
  langs:
  - csharp
  - vb
  name: Application.Questions.Commands.UpdateQuestion.Models
  nameWithType: Application.Questions.Commands.UpdateQuestion.Models
  fullName: Application.Questions.Commands.UpdateQuestion.Models
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Questions.Commands.UpdateQuestion.Models.QuestionSourceUpdateCommand
  commentId: T:Application.Questions.Commands.UpdateQuestion.Models.QuestionSourceUpdateCommand
  href: Application.Questions.Commands.UpdateQuestion.Models.QuestionSourceUpdateCommand.html
  name: QuestionSourceUpdateCommand
  nameWithType: QuestionSourceUpdateCommand
  fullName: Application.Questions.Commands.UpdateQuestion.Models.QuestionSourceUpdateCommand
