### YamlMime:ManagedReference
items:
- uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery
  commentId: T:Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery
  id: EntityTimelineDetailsQuery
  parent: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  children:
  - Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityId
  - Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityName
  - Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.TimelineId
  langs:
  - csharp
  - vb
  name: EntityTimelineDetailsQuery
  nameWithType: EntityTimelineDetailsQuery
  fullName: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery
  type: Class
  source:
    remote:
      path: src/Application/EntitlesTimeline/Queries/EntityTimelineDetails/EntityTimelineDetailsQuery.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: EntityTimelineDetailsQuery
    path: src/Application/EntitlesTimeline/Queries/EntityTimelineDetails/EntityTimelineDetailsQuery.cs
    startLine: 7
  assemblies:
  - Application
  namespace: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  syntax:
    content: 'public class EntityTimelineDetailsQuery : IRequest<Result<EntityTimelineDetailsQueryResult>>, IBaseRequest'
    content.vb: Public Class EntityTimelineDetailsQuery Implements IRequest(Of Result(Of EntityTimelineDetailsQueryResult)), IBaseRequest
  inheritance:
  - System.Object
  implements:
  - MediatR.IRequest{Application.Commons.Models.Results.Result{Application.Commons.SharedModelResult.Timeline.EntityTimelineDetails.EntityTimelineDetailsQueryResult}}
  - MediatR.IBaseRequest
  extensionMethods:
  - System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  - System.Object.Domain.Extentions.ObjectExtention.IsNull
- uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.TimelineId
  commentId: P:Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.TimelineId
  id: TimelineId
  parent: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery
  langs:
  - csharp
  - vb
  name: TimelineId
  nameWithType: EntityTimelineDetailsQuery.TimelineId
  fullName: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.TimelineId
  type: Property
  source:
    remote:
      path: src/Application/EntitlesTimeline/Queries/EntityTimelineDetails/EntityTimelineDetailsQuery.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: TimelineId
    path: src/Application/EntitlesTimeline/Queries/EntityTimelineDetails/EntityTimelineDetailsQuery.cs
    startLine: 9
  assemblies:
  - Application
  namespace: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  syntax:
    content: public Guid TimelineId { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property TimelineId As Guid
  overload: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.TimelineId*
- uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityName
  commentId: P:Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityName
  id: EntityName
  parent: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery
  langs:
  - csharp
  - vb
  name: EntityName
  nameWithType: EntityTimelineDetailsQuery.EntityName
  fullName: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityName
  type: Property
  source:
    remote:
      path: src/Application/EntitlesTimeline/Queries/EntityTimelineDetails/EntityTimelineDetailsQuery.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: EntityName
    path: src/Application/EntitlesTimeline/Queries/EntityTimelineDetails/EntityTimelineDetailsQuery.cs
    startLine: 10
  assemblies:
  - Application
  namespace: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  syntax:
    content: public EntityName EntityName { get; set; }
    parameters: []
    return:
      type: Domain.Enums.EntityName
    content.vb: Public Property EntityName As EntityName
  overload: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityName*
- uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityId
  commentId: P:Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityId
  id: EntityId
  parent: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery
  langs:
  - csharp
  - vb
  name: EntityId
  nameWithType: EntityTimelineDetailsQuery.EntityId
  fullName: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityId
  type: Property
  source:
    remote:
      path: src/Application/EntitlesTimeline/Queries/EntityTimelineDetails/EntityTimelineDetailsQuery.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: EntityId
    path: src/Application/EntitlesTimeline/Queries/EntityTimelineDetails/EntityTimelineDetailsQuery.cs
    startLine: 11
  assemblies:
  - Application
  namespace: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  syntax:
    content: public Guid EntityId { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property EntityId As Guid
  overload: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityId*
references:
- uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  commentId: N:Application.EntitlesTimeline.Queries.EntityTimelineDetails
  href: Application.html
  name: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  nameWithType: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  fullName: Application.EntitlesTimeline.Queries.EntityTimelineDetails
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.EntitlesTimeline
    name: EntitlesTimeline
    href: Application.EntitlesTimeline.html
  - name: .
  - uid: Application.EntitlesTimeline.Queries
    name: Queries
    href: Application.EntitlesTimeline.Queries.html
  - name: .
  - uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails
    name: EntityTimelineDetails
    href: Application.EntitlesTimeline.Queries.EntityTimelineDetails.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.EntitlesTimeline
    name: EntitlesTimeline
    href: Application.EntitlesTimeline.html
  - name: .
  - uid: Application.EntitlesTimeline.Queries
    name: Queries
    href: Application.EntitlesTimeline.Queries.html
  - name: .
  - uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails
    name: EntityTimelineDetails
    href: Application.EntitlesTimeline.Queries.EntityTimelineDetails.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MediatR.IRequest{Application.Commons.Models.Results.Result{Application.Commons.SharedModelResult.Timeline.EntityTimelineDetails.EntityTimelineDetailsQueryResult}}
  commentId: T:MediatR.IRequest{Application.Commons.Models.Results.Result{Application.Commons.SharedModelResult.Timeline.EntityTimelineDetails.EntityTimelineDetailsQueryResult}}
  parent: MediatR
  definition: MediatR.IRequest`1
  href: Application.Commons.Models.Results.Result-1.html
  name: IRequest<Result<EntityTimelineDetailsQueryResult>>
  nameWithType: IRequest<Result<EntityTimelineDetailsQueryResult>>
  fullName: MediatR.IRequest<Application.Commons.Models.Results.Result<Application.Commons.SharedModelResult.Timeline.EntityTimelineDetails.EntityTimelineDetailsQueryResult>>
  nameWithType.vb: IRequest(Of Result(Of EntityTimelineDetailsQueryResult))
  fullName.vb: MediatR.IRequest(Of Application.Commons.Models.Results.Result(Of Application.Commons.SharedModelResult.Timeline.EntityTimelineDetails.EntityTimelineDetailsQueryResult))
  name.vb: IRequest(Of Result(Of EntityTimelineDetailsQueryResult))
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - uid: Application.Commons.Models.Results.Result`1
    name: Result
    href: Application.Commons.Models.Results.Result-1.html
  - name: <
  - uid: Application.Commons.SharedModelResult.Timeline.EntityTimelineDetails.EntityTimelineDetailsQueryResult
    name: EntityTimelineDetailsQueryResult
    href: Application.Commons.SharedModelResult.Timeline.EntityTimelineDetails.EntityTimelineDetailsQueryResult.html
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Application.Commons.Models.Results.Result`1
    name: Result
    href: Application.Commons.Models.Results.Result-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: Application.Commons.SharedModelResult.Timeline.EntityTimelineDetails.EntityTimelineDetailsQueryResult
    name: EntityTimelineDetailsQueryResult
    href: Application.Commons.SharedModelResult.Timeline.EntityTimelineDetails.EntityTimelineDetailsQueryResult.html
  - name: )
  - name: )
- uid: MediatR.IBaseRequest
  commentId: T:MediatR.IBaseRequest
  parent: MediatR
  isExternal: true
  name: IBaseRequest
  nameWithType: IBaseRequest
  fullName: MediatR.IBaseRequest
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MediatR.IRequest`1
  commentId: T:MediatR.IRequest`1
  isExternal: true
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: MediatR.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: MediatR.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: MediatR
  commentId: N:MediatR
  isExternal: true
  name: MediatR
  nameWithType: MediatR
  fullName: MediatR
- uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions.ObjectExtention
  commentId: T:Domain.Extentions.ObjectExtention
  parent: Domain.Extentions
  href: Domain.Extentions.ObjectExtention.html
  name: ObjectExtention
  nameWithType: ObjectExtention
  fullName: Domain.Extentions.ObjectExtention
- uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions
  commentId: N:Domain.Extentions
  href: Domain.html
  name: Domain.Extentions
  nameWithType: Domain.Extentions
  fullName: Domain.Extentions
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
- uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.TimelineId*
  commentId: Overload:Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.TimelineId
  href: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.html#Application_EntitlesTimeline_Queries_EntityTimelineDetails_EntityTimelineDetailsQuery_TimelineId
  name: TimelineId
  nameWithType: EntityTimelineDetailsQuery.TimelineId
  fullName: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.TimelineId
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityName*
  commentId: Overload:Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityName
  href: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.html#Application_EntitlesTimeline_Queries_EntityTimelineDetails_EntityTimelineDetailsQuery_EntityName
  name: EntityName
  nameWithType: EntityTimelineDetailsQuery.EntityName
  fullName: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityName
- uid: Domain.Enums.EntityName
  commentId: T:Domain.Enums.EntityName
  parent: Domain.Enums
  href: Domain.Enums.EntityName.html
  name: EntityName
  nameWithType: EntityName
  fullName: Domain.Enums.EntityName
- uid: Domain.Enums
  commentId: N:Domain.Enums
  href: Domain.html
  name: Domain.Enums
  nameWithType: Domain.Enums
  fullName: Domain.Enums
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Enums
    name: Enums
    href: Domain.Enums.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Enums
    name: Enums
    href: Domain.Enums.html
- uid: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityId*
  commentId: Overload:Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityId
  href: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.html#Application_EntitlesTimeline_Queries_EntityTimelineDetails_EntityTimelineDetailsQuery_EntityId
  name: EntityId
  nameWithType: EntityTimelineDetailsQuery.EntityId
  fullName: Application.EntitlesTimeline.Queries.EntityTimelineDetails.EntityTimelineDetailsQuery.EntityId
