### YamlMime:ManagedReference
items:
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult
  commentId: T:Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult
  id: TrueFalseQuestionQueryResult
  parent: Application.Questions.Queries.GetQuestionsById.ResultModel
  children:
  - Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Feedback
  - Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Id
  - Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.IsCorrect
  langs:
  - csharp
  - vb
  name: TrueFalseQuestionQueryResult
  nameWithType: TrueFalseQuestionQueryResult
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult
  type: Class
  source:
    remote:
      path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/TrueFalseQuestionQueryResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: TrueFalseQuestionQueryResult
    path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/TrueFalseQuestionQueryResult.cs
    startLine: 2
  assemblies:
  - Application
  namespace: Application.Questions.Queries.GetQuestionsById.ResultModel
  syntax:
    content: public class TrueFalseQuestionQueryResult
    content.vb: Public Class TrueFalseQuestionQueryResult
  inheritance:
  - System.Object
  extensionMethods:
  - System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  - System.Object.Domain.Extentions.ObjectExtention.IsNull
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Id
  commentId: P:Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Id
  id: Id
  parent: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: TrueFalseQuestionQueryResult.Id
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Id
  type: Property
  source:
    remote:
      path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/TrueFalseQuestionQueryResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Id
    path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/TrueFalseQuestionQueryResult.cs
    startLine: 4
  assemblies:
  - Application
  namespace: Application.Questions.Queries.GetQuestionsById.ResultModel
  syntax:
    content: public Guid Id { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property Id As Guid
  overload: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Id*
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.IsCorrect
  commentId: P:Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.IsCorrect
  id: IsCorrect
  parent: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult
  langs:
  - csharp
  - vb
  name: IsCorrect
  nameWithType: TrueFalseQuestionQueryResult.IsCorrect
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.IsCorrect
  type: Property
  source:
    remote:
      path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/TrueFalseQuestionQueryResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: IsCorrect
    path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/TrueFalseQuestionQueryResult.cs
    startLine: 5
  assemblies:
  - Application
  namespace: Application.Questions.Queries.GetQuestionsById.ResultModel
  syntax:
    content: public bool IsCorrect { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsCorrect As Boolean
  overload: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.IsCorrect*
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Feedback
  commentId: P:Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Feedback
  id: Feedback
  parent: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult
  langs:
  - csharp
  - vb
  name: Feedback
  nameWithType: TrueFalseQuestionQueryResult.Feedback
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Feedback
  type: Property
  source:
    remote:
      path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/TrueFalseQuestionQueryResult.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Feedback
    path: src/Application/Questions/Queries/GetQuestionsById/ResultModel/TrueFalseQuestionQueryResult.cs
    startLine: 6
  assemblies:
  - Application
  namespace: Application.Questions.Queries.GetQuestionsById.ResultModel
  syntax:
    content: public FeedbackQueryResult? Feedback { get; set; }
    parameters: []
    return:
      type: Application.Questions.Queries.GetQuestionsById.ResultModel.FeedbackQueryResult
    content.vb: Public Property Feedback As FeedbackQueryResult
  overload: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Feedback*
references:
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel
  commentId: N:Application.Questions.Queries.GetQuestionsById.ResultModel
  href: Application.html
  name: Application.Questions.Queries.GetQuestionsById.ResultModel
  nameWithType: Application.Questions.Queries.GetQuestionsById.ResultModel
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Questions
    name: Questions
    href: Application.Questions.html
  - name: .
  - uid: Application.Questions.Queries
    name: Queries
    href: Application.Questions.Queries.html
  - name: .
  - uid: Application.Questions.Queries.GetQuestionsById
    name: GetQuestionsById
    href: Application.Questions.Queries.GetQuestionsById.html
  - name: .
  - uid: Application.Questions.Queries.GetQuestionsById.ResultModel
    name: ResultModel
    href: Application.Questions.Queries.GetQuestionsById.ResultModel.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Questions
    name: Questions
    href: Application.Questions.html
  - name: .
  - uid: Application.Questions.Queries
    name: Queries
    href: Application.Questions.Queries.html
  - name: .
  - uid: Application.Questions.Queries.GetQuestionsById
    name: GetQuestionsById
    href: Application.Questions.Queries.GetQuestionsById.html
  - name: .
  - uid: Application.Questions.Queries.GetQuestionsById.ResultModel
    name: ResultModel
    href: Application.Questions.Queries.GetQuestionsById.ResultModel.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions.ObjectExtention
  commentId: T:Domain.Extentions.ObjectExtention
  parent: Domain.Extentions
  href: Domain.Extentions.ObjectExtention.html
  name: ObjectExtention
  nameWithType: ObjectExtention
  fullName: Domain.Extentions.ObjectExtention
- uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions
  commentId: N:Domain.Extentions
  href: Domain.html
  name: Domain.Extentions
  nameWithType: Domain.Extentions
  fullName: Domain.Extentions
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Id*
  commentId: Overload:Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Id
  href: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.html#Application_Questions_Queries_GetQuestionsById_ResultModel_TrueFalseQuestionQueryResult_Id
  name: Id
  nameWithType: TrueFalseQuestionQueryResult.Id
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Id
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.IsCorrect*
  commentId: Overload:Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.IsCorrect
  href: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.html#Application_Questions_Queries_GetQuestionsById_ResultModel_TrueFalseQuestionQueryResult_IsCorrect
  name: IsCorrect
  nameWithType: TrueFalseQuestionQueryResult.IsCorrect
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.IsCorrect
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Feedback*
  commentId: Overload:Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Feedback
  href: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.html#Application_Questions_Queries_GetQuestionsById_ResultModel_TrueFalseQuestionQueryResult_Feedback
  name: Feedback
  nameWithType: TrueFalseQuestionQueryResult.Feedback
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.TrueFalseQuestionQueryResult.Feedback
- uid: Application.Questions.Queries.GetQuestionsById.ResultModel.FeedbackQueryResult
  commentId: T:Application.Questions.Queries.GetQuestionsById.ResultModel.FeedbackQueryResult
  parent: Application.Questions.Queries.GetQuestionsById.ResultModel
  href: Application.Questions.Queries.GetQuestionsById.ResultModel.FeedbackQueryResult.html
  name: FeedbackQueryResult
  nameWithType: FeedbackQueryResult
  fullName: Application.Questions.Queries.GetQuestionsById.ResultModel.FeedbackQueryResult
