### YamlMime:ManagedReference
items:
- uid: Application.Commons.Models.Results
  commentId: N:Application.Commons.Models.Results
  id: Application.Commons.Models.Results
  children:
  - Application.Commons.Models.Results.PartialsSuccessResult
  - Application.Commons.Models.Results.Result
  - Application.Commons.Models.Results.Result`1
  langs:
  - csharp
  - vb
  name: Application.Commons.Models.Results
  nameWithType: Application.Commons.Models.Results
  fullName: Application.Commons.Models.Results
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Commons.Models.Results.PartialsSuccessResult
  commentId: T:Application.Commons.Models.Results.PartialsSuccessResult
  href: Application.Commons.Models.Results.PartialsSuccessResult.html
  name: PartialsSuccessResult
  nameWithType: PartialsSuccessResult
  fullName: Application.Commons.Models.Results.PartialsSuccessResult
- uid: Application.Commons.Models.Results.Result`1
  commentId: T:Application.Commons.Models.Results.Result`1
  parent: Application.Commons.Models.Results
  href: Application.Commons.Models.Results.Result-1.html
  name: Result<T>
  nameWithType: Result<T>
  fullName: Application.Commons.Models.Results.Result<T>
  nameWithType.vb: Result(Of T)
  fullName.vb: Application.Commons.Models.Results.Result(Of T)
  name.vb: Result(Of T)
  spec.csharp:
  - uid: Application.Commons.Models.Results.Result`1
    name: Result
    href: Application.Commons.Models.Results.Result-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Application.Commons.Models.Results.Result`1
    name: Result
    href: Application.Commons.Models.Results.Result-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Application.Commons.Models.Results.Result
  commentId: T:Application.Commons.Models.Results.Result
  parent: Application.Commons.Models.Results
  href: Application.Commons.Models.Results.Result.html
  name: Result
  nameWithType: Result
  fullName: Application.Commons.Models.Results.Result
- uid: Application.Commons.Models.Results
  commentId: N:Application.Commons.Models.Results
  href: Application.html
  name: Application.Commons.Models.Results
  nameWithType: Application.Commons.Models.Results
  fullName: Application.Commons.Models.Results
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Models
    name: Models
    href: Application.Commons.Models.html
  - name: .
  - uid: Application.Commons.Models.Results
    name: Results
    href: Application.Commons.Models.Results.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.Models
    name: Models
    href: Application.Commons.Models.html
  - name: .
  - uid: Application.Commons.Models.Results
    name: Results
    href: Application.Commons.Models.Results.html
