### YamlMime:ManagedReference
items:
- uid: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
  commentId: N:Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
  id: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
  children:
  - Application.Auditing.ApplicationLogs.Queries.LogSearchQuery.LogSearchQuery
  - Application.Auditing.ApplicationLogs.Queries.LogSearchQuery.LogSearchQueryHandler
  langs:
  - csharp
  - vb
  name: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
  nameWithType: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
  fullName: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery.LogSearchQuery
  commentId: T:Application.Auditing.ApplicationLogs.Queries.LogSearchQuery.LogSearchQuery
  parent: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
  href: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery.LogSearchQuery.html
  name: LogSearchQuery
  nameWithType: LogSearchQuery
  fullName: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery.LogSearchQuery
- uid: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery.LogSearchQueryHandler
  commentId: T:Application.Auditing.ApplicationLogs.Queries.LogSearchQuery.LogSearchQueryHandler
  href: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery.LogSearchQueryHandler.html
  name: LogSearchQueryHandler
  nameWithType: LogSearchQueryHandler
  fullName: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery.LogSearchQueryHandler
- uid: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
  commentId: N:Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
  href: Application.html
  name: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
  nameWithType: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
  fullName: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Auditing
    name: Auditing
    href: Application.Auditing.html
  - name: .
  - uid: Application.Auditing.ApplicationLogs
    name: ApplicationLogs
    href: Application.Auditing.ApplicationLogs.html
  - name: .
  - uid: Application.Auditing.ApplicationLogs.Queries
    name: Queries
    href: Application.Auditing.ApplicationLogs.Queries.html
  - name: .
  - uid: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
    name: LogSearchQuery
    href: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Auditing
    name: Auditing
    href: Application.Auditing.html
  - name: .
  - uid: Application.Auditing.ApplicationLogs
    name: ApplicationLogs
    href: Application.Auditing.ApplicationLogs.html
  - name: .
  - uid: Application.Auditing.ApplicationLogs.Queries
    name: Queries
    href: Application.Auditing.ApplicationLogs.Queries.html
  - name: .
  - uid: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery
    name: LogSearchQuery
    href: Application.Auditing.ApplicationLogs.Queries.LogSearchQuery.html
