### YamlMime:ManagedReference
items:
- uid: Application.Sources.Queries.GetSourceReferences
  commentId: N:Application.Sources.Queries.GetSourceReferences
  id: Application.Sources.Queries.GetSourceReferences
  children:
  - Application.Sources.Queries.GetSourceReferences.GetSourceReferencesQuery
  - Application.Sources.Queries.GetSourceReferences.GetSourceReferencesQueryResult
  langs:
  - csharp
  - vb
  name: Application.Sources.Queries.GetSourceReferences
  nameWithType: Application.Sources.Queries.GetSourceReferences
  fullName: Application.Sources.Queries.GetSourceReferences
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Sources.Queries.GetSourceReferences.GetSourceReferencesQuery
  commentId: T:Application.Sources.Queries.GetSourceReferences.GetSourceReferencesQuery
  href: Application.Sources.Queries.GetSourceReferences.GetSourceReferencesQuery.html
  name: GetSourceReferencesQuery
  nameWithType: GetSourceReferencesQuery
  fullName: Application.Sources.Queries.GetSourceReferences.GetSourceReferencesQuery
- uid: Application.Sources.Queries.GetSourceReferences.GetSourceReferencesQueryResult
  commentId: T:Application.Sources.Queries.GetSourceReferences.GetSourceReferencesQueryResult
  href: Application.Sources.Queries.GetSourceReferences.GetSourceReferencesQueryResult.html
  name: GetSourceReferencesQueryResult
  nameWithType: GetSourceReferencesQueryResult
  fullName: Application.Sources.Queries.GetSourceReferences.GetSourceReferencesQueryResult
