### YamlMime:ManagedReference
items:
- uid: Application
  commentId: N:Application
  id: Application
  children:
  - Application.ApplicationRegisterServices
  langs:
  - csharp
  - vb
  name: Application
  nameWithType: Application
  fullName: Application
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.ApplicationRegisterServices
  commentId: T:Application.ApplicationRegisterServices
  href: Application.ApplicationRegisterServices.html
  name: ApplicationRegisterServices
  nameWithType: ApplicationRegisterServices
  fullName: Application.ApplicationRegisterServices
