### YamlMime:ManagedReference
items:
- uid: Application.Tags.Commands.UpdateTag.UpdateTagCommand
  commentId: T:Application.Tags.Commands.UpdateTag.UpdateTagCommand
  id: UpdateTagCommand
  parent: Application.Tags.Commands.UpdateTag
  children:
  - Application.Tags.Commands.UpdateTag.UpdateTagCommand.BackgroundColorCode
  - Application.Tags.Commands.UpdateTag.UpdateTagCommand.Id
  - Application.Tags.Commands.UpdateTag.UpdateTagCommand.Name
  - Application.Tags.Commands.UpdateTag.UpdateTagCommand.TextColorCode
  langs:
  - csharp
  - vb
  name: UpdateTagCommand
  nameWithType: UpdateTagCommand
  fullName: Application.Tags.Commands.UpdateTag.UpdateTagCommand
  type: Class
  source:
    remote:
      path: src/Application/Tags/Commands/UpdateTag/UpdateTagCommand.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: UpdateTagCommand
    path: src/Application/Tags/Commands/UpdateTag/UpdateTagCommand.cs
    startLine: 5
  assemblies:
  - Application
  namespace: Application.Tags.Commands.UpdateTag
  syntax:
    content: 'public class UpdateTagCommand : IRequest<Result>, IBaseRequest'
    content.vb: Public Class UpdateTagCommand Implements IRequest(Of Result), IBaseRequest
  inheritance:
  - System.Object
  implements:
  - MediatR.IRequest{Application.Commons.Models.Results.Result}
  - MediatR.IBaseRequest
  extensionMethods:
  - System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  - System.Object.Domain.Extentions.ObjectExtention.IsNull
- uid: Application.Tags.Commands.UpdateTag.UpdateTagCommand.Id
  commentId: P:Application.Tags.Commands.UpdateTag.UpdateTagCommand.Id
  id: Id
  parent: Application.Tags.Commands.UpdateTag.UpdateTagCommand
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: UpdateTagCommand.Id
  fullName: Application.Tags.Commands.UpdateTag.UpdateTagCommand.Id
  type: Property
  source:
    remote:
      path: src/Application/Tags/Commands/UpdateTag/UpdateTagCommand.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Id
    path: src/Application/Tags/Commands/UpdateTag/UpdateTagCommand.cs
    startLine: 7
  assemblies:
  - Application
  namespace: Application.Tags.Commands.UpdateTag
  syntax:
    content: public Guid Id { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property Id As Guid
  overload: Application.Tags.Commands.UpdateTag.UpdateTagCommand.Id*
- uid: Application.Tags.Commands.UpdateTag.UpdateTagCommand.Name
  commentId: P:Application.Tags.Commands.UpdateTag.UpdateTagCommand.Name
  id: Name
  parent: Application.Tags.Commands.UpdateTag.UpdateTagCommand
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: UpdateTagCommand.Name
  fullName: Application.Tags.Commands.UpdateTag.UpdateTagCommand.Name
  type: Property
  source:
    remote:
      path: src/Application/Tags/Commands/UpdateTag/UpdateTagCommand.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Name
    path: src/Application/Tags/Commands/UpdateTag/UpdateTagCommand.cs
    startLine: 8
  assemblies:
  - Application
  namespace: Application.Tags.Commands.UpdateTag
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: Application.Tags.Commands.UpdateTag.UpdateTagCommand.Name*
- uid: Application.Tags.Commands.UpdateTag.UpdateTagCommand.BackgroundColorCode
  commentId: P:Application.Tags.Commands.UpdateTag.UpdateTagCommand.BackgroundColorCode
  id: BackgroundColorCode
  parent: Application.Tags.Commands.UpdateTag.UpdateTagCommand
  langs:
  - csharp
  - vb
  name: BackgroundColorCode
  nameWithType: UpdateTagCommand.BackgroundColorCode
  fullName: Application.Tags.Commands.UpdateTag.UpdateTagCommand.BackgroundColorCode
  type: Property
  source:
    remote:
      path: src/Application/Tags/Commands/UpdateTag/UpdateTagCommand.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: BackgroundColorCode
    path: src/Application/Tags/Commands/UpdateTag/UpdateTagCommand.cs
    startLine: 9
  assemblies:
  - Application
  namespace: Application.Tags.Commands.UpdateTag
  syntax:
    content: public string? BackgroundColorCode { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BackgroundColorCode As String
  overload: Application.Tags.Commands.UpdateTag.UpdateTagCommand.BackgroundColorCode*
- uid: Application.Tags.Commands.UpdateTag.UpdateTagCommand.TextColorCode
  commentId: P:Application.Tags.Commands.UpdateTag.UpdateTagCommand.TextColorCode
  id: TextColorCode
  parent: Application.Tags.Commands.UpdateTag.UpdateTagCommand
  langs:
  - csharp
  - vb
  name: TextColorCode
  nameWithType: UpdateTagCommand.TextColorCode
  fullName: Application.Tags.Commands.UpdateTag.UpdateTagCommand.TextColorCode
  type: Property
  source:
    remote:
      path: src/Application/Tags/Commands/UpdateTag/UpdateTagCommand.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: TextColorCode
    path: src/Application/Tags/Commands/UpdateTag/UpdateTagCommand.cs
    startLine: 10
  assemblies:
  - Application
  namespace: Application.Tags.Commands.UpdateTag
  syntax:
    content: public string? TextColorCode { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property TextColorCode As String
  overload: Application.Tags.Commands.UpdateTag.UpdateTagCommand.TextColorCode*
references:
- uid: Application.Tags.Commands.UpdateTag
  commentId: N:Application.Tags.Commands.UpdateTag
  href: Application.html
  name: Application.Tags.Commands.UpdateTag
  nameWithType: Application.Tags.Commands.UpdateTag
  fullName: Application.Tags.Commands.UpdateTag
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Tags
    name: Tags
    href: Application.Tags.html
  - name: .
  - uid: Application.Tags.Commands
    name: Commands
    href: Application.Tags.Commands.html
  - name: .
  - uid: Application.Tags.Commands.UpdateTag
    name: UpdateTag
    href: Application.Tags.Commands.UpdateTag.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Tags
    name: Tags
    href: Application.Tags.html
  - name: .
  - uid: Application.Tags.Commands
    name: Commands
    href: Application.Tags.Commands.html
  - name: .
  - uid: Application.Tags.Commands.UpdateTag
    name: UpdateTag
    href: Application.Tags.Commands.UpdateTag.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MediatR.IRequest{Application.Commons.Models.Results.Result}
  commentId: T:MediatR.IRequest{Application.Commons.Models.Results.Result}
  parent: MediatR
  definition: MediatR.IRequest`1
  href: Application.Commons.Models.Results.Result.html
  name: IRequest<Result>
  nameWithType: IRequest<Result>
  fullName: MediatR.IRequest<Application.Commons.Models.Results.Result>
  nameWithType.vb: IRequest(Of Result)
  fullName.vb: MediatR.IRequest(Of Application.Commons.Models.Results.Result)
  name.vb: IRequest(Of Result)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - uid: Application.Commons.Models.Results.Result
    name: Result
    href: Application.Commons.Models.Results.Result.html
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Application.Commons.Models.Results.Result
    name: Result
    href: Application.Commons.Models.Results.Result.html
  - name: )
- uid: MediatR.IBaseRequest
  commentId: T:MediatR.IBaseRequest
  parent: MediatR
  isExternal: true
  name: IBaseRequest
  nameWithType: IBaseRequest
  fullName: MediatR.IBaseRequest
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MediatR.IRequest`1
  commentId: T:MediatR.IRequest`1
  isExternal: true
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: MediatR.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: MediatR.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: MediatR
  commentId: N:MediatR
  isExternal: true
  name: MediatR
  nameWithType: MediatR
  fullName: MediatR
- uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions.ObjectExtention
  commentId: T:Domain.Extentions.ObjectExtention
  parent: Domain.Extentions
  href: Domain.Extentions.ObjectExtention.html
  name: ObjectExtention
  nameWithType: ObjectExtention
  fullName: Domain.Extentions.ObjectExtention
- uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions
  commentId: N:Domain.Extentions
  href: Domain.html
  name: Domain.Extentions
  nameWithType: Domain.Extentions
  fullName: Domain.Extentions
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
- uid: Application.Tags.Commands.UpdateTag.UpdateTagCommand.Id*
  commentId: Overload:Application.Tags.Commands.UpdateTag.UpdateTagCommand.Id
  href: Application.Tags.Commands.UpdateTag.UpdateTagCommand.html#Application_Tags_Commands_UpdateTag_UpdateTagCommand_Id
  name: Id
  nameWithType: UpdateTagCommand.Id
  fullName: Application.Tags.Commands.UpdateTag.UpdateTagCommand.Id
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: Application.Tags.Commands.UpdateTag.UpdateTagCommand.Name*
  commentId: Overload:Application.Tags.Commands.UpdateTag.UpdateTagCommand.Name
  href: Application.Tags.Commands.UpdateTag.UpdateTagCommand.html#Application_Tags_Commands_UpdateTag_UpdateTagCommand_Name
  name: Name
  nameWithType: UpdateTagCommand.Name
  fullName: Application.Tags.Commands.UpdateTag.UpdateTagCommand.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Application.Tags.Commands.UpdateTag.UpdateTagCommand.BackgroundColorCode*
  commentId: Overload:Application.Tags.Commands.UpdateTag.UpdateTagCommand.BackgroundColorCode
  href: Application.Tags.Commands.UpdateTag.UpdateTagCommand.html#Application_Tags_Commands_UpdateTag_UpdateTagCommand_BackgroundColorCode
  name: BackgroundColorCode
  nameWithType: UpdateTagCommand.BackgroundColorCode
  fullName: Application.Tags.Commands.UpdateTag.UpdateTagCommand.BackgroundColorCode
- uid: Application.Tags.Commands.UpdateTag.UpdateTagCommand.TextColorCode*
  commentId: Overload:Application.Tags.Commands.UpdateTag.UpdateTagCommand.TextColorCode
  href: Application.Tags.Commands.UpdateTag.UpdateTagCommand.html#Application_Tags_Commands_UpdateTag_UpdateTagCommand_TextColorCode
  name: TextColorCode
  nameWithType: UpdateTagCommand.TextColorCode
  fullName: Application.Tags.Commands.UpdateTag.UpdateTagCommand.TextColorCode
