### YamlMime:ManagedReference
items:
- uid: Application.Tags.Queries.GetTagDetails
  commentId: N:Application.Tags.Queries.GetTagDetails
  id: Application.Tags.Queries.GetTagDetails
  children:
  - Application.Tags.Queries.GetTagDetails.GetTagDetailsQuery
  - Application.Tags.Queries.GetTagDetails.GetTagDetailsQueryHandler
  - Application.Tags.Queries.GetTagDetails.GetTagDetailsQueryResult
  langs:
  - csharp
  - vb
  name: Application.Tags.Queries.GetTagDetails
  nameWithType: Application.Tags.Queries.GetTagDetails
  fullName: Application.Tags.Queries.GetTagDetails
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Tags.Queries.GetTagDetails.GetTagDetailsQuery
  commentId: T:Application.Tags.Queries.GetTagDetails.GetTagDetailsQuery
  parent: Application.Tags.Queries.GetTagDetails
  href: Application.Tags.Queries.GetTagDetails.GetTagDetailsQuery.html
  name: GetTagDetailsQuery
  nameWithType: GetTagDetailsQuery
  fullName: Application.Tags.Queries.GetTagDetails.GetTagDetailsQuery
- uid: Application.Tags.Queries.GetTagDetails.GetTagDetailsQueryHandler
  commentId: T:Application.Tags.Queries.GetTagDetails.GetTagDetailsQueryHandler
  href: Application.Tags.Queries.GetTagDetails.GetTagDetailsQueryHandler.html
  name: GetTagDetailsQueryHandler
  nameWithType: GetTagDetailsQueryHandler
  fullName: Application.Tags.Queries.GetTagDetails.GetTagDetailsQueryHandler
- uid: Application.Tags.Queries.GetTagDetails.GetTagDetailsQueryResult
  commentId: T:Application.Tags.Queries.GetTagDetails.GetTagDetailsQueryResult
  href: Application.Tags.Queries.GetTagDetails.GetTagDetailsQueryResult.html
  name: GetTagDetailsQueryResult
  nameWithType: GetTagDetailsQueryResult
  fullName: Application.Tags.Queries.GetTagDetails.GetTagDetailsQueryResult
- uid: Application.Tags.Queries.GetTagDetails
  commentId: N:Application.Tags.Queries.GetTagDetails
  href: Application.html
  name: Application.Tags.Queries.GetTagDetails
  nameWithType: Application.Tags.Queries.GetTagDetails
  fullName: Application.Tags.Queries.GetTagDetails
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Tags
    name: Tags
    href: Application.Tags.html
  - name: .
  - uid: Application.Tags.Queries
    name: Queries
    href: Application.Tags.Queries.html
  - name: .
  - uid: Application.Tags.Queries.GetTagDetails
    name: GetTagDetails
    href: Application.Tags.Queries.GetTagDetails.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Tags
    name: Tags
    href: Application.Tags.html
  - name: .
  - uid: Application.Tags.Queries
    name: Queries
    href: Application.Tags.Queries.html
  - name: .
  - uid: Application.Tags.Queries.GetTagDetails
    name: GetTagDetails
    href: Application.Tags.Queries.GetTagDetails.html
