### YamlMime:ManagedReference
items:
- uid: Application.Sources.Commands.AddSource.Results
  commentId: N:Application.Sources.Commands.AddSource.Results
  id: Application.Sources.Commands.AddSource.Results
  children:
  - Application.Sources.Commands.AddSource.Results.AddSourceCommandResult
  - Application.Sources.Commands.AddSource.Results.SourceReferenceResult
  langs:
  - csharp
  - vb
  name: Application.Sources.Commands.AddSource.Results
  nameWithType: Application.Sources.Commands.AddSource.Results
  fullName: Application.Sources.Commands.AddSource.Results
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Sources.Commands.AddSource.Results.AddSourceCommandResult
  commentId: T:Application.Sources.Commands.AddSource.Results.AddSourceCommandResult
  href: Application.Sources.Commands.AddSource.Results.AddSourceCommandResult.html
  name: AddSourceCommandResult
  nameWithType: AddSourceCommandResult
  fullName: Application.Sources.Commands.AddSource.Results.AddSourceCommandResult
- uid: Application.Sources.Commands.AddSource.Results.SourceReferenceResult
  commentId: T:Application.Sources.Commands.AddSource.Results.SourceReferenceResult
  href: Application.Sources.Commands.AddSource.Results.SourceReferenceResult.html
  name: SourceReferenceResult
  nameWithType: SourceReferenceResult
  fullName: Application.Sources.Commands.AddSource.Results.SourceReferenceResult
