### YamlMime:ManagedReference
items:
- uid: Application.Categories.Queries.GetAllCategory
  commentId: N:Application.Categories.Queries.GetAllCategory
  id: Application.Categories.Queries.GetAllCategory
  children:
  - Application.Categories.Queries.GetAllCategory.GetAllCategoryQuery
  - Application.Categories.Queries.GetAllCategory.GetAllCategoryQueryHandler
  - Application.Categories.Queries.GetAllCategory.GetAllCategoryQueryResult
  langs:
  - csharp
  - vb
  name: Application.Categories.Queries.GetAllCategory
  nameWithType: Application.Categories.Queries.GetAllCategory
  fullName: Application.Categories.Queries.GetAllCategory
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Categories.Queries.GetAllCategory.GetAllCategoryQuery
  commentId: T:Application.Categories.Queries.GetAllCategory.GetAllCategoryQuery
  parent: Application.Categories.Queries.GetAllCategory
  href: Application.Categories.Queries.GetAllCategory.GetAllCategoryQuery.html
  name: GetAllCategoryQuery
  nameWithType: GetAllCategoryQuery
  fullName: Application.Categories.Queries.GetAllCategory.GetAllCategoryQuery
- uid: Application.Categories.Queries.GetAllCategory.GetAllCategoryQueryHandler
  commentId: T:Application.Categories.Queries.GetAllCategory.GetAllCategoryQueryHandler
  href: Application.Categories.Queries.GetAllCategory.GetAllCategoryQueryHandler.html
  name: GetAllCategoryQueryHandler
  nameWithType: GetAllCategoryQueryHandler
  fullName: Application.Categories.Queries.GetAllCategory.GetAllCategoryQueryHandler
- uid: Application.Categories.Queries.GetAllCategory.GetAllCategoryQueryResult
  commentId: T:Application.Categories.Queries.GetAllCategory.GetAllCategoryQueryResult
  href: Application.Categories.Queries.GetAllCategory.GetAllCategoryQueryResult.html
  name: GetAllCategoryQueryResult
  nameWithType: GetAllCategoryQueryResult
  fullName: Application.Categories.Queries.GetAllCategory.GetAllCategoryQueryResult
- uid: Application.Categories.Queries.GetAllCategory
  commentId: N:Application.Categories.Queries.GetAllCategory
  href: Application.html
  name: Application.Categories.Queries.GetAllCategory
  nameWithType: Application.Categories.Queries.GetAllCategory
  fullName: Application.Categories.Queries.GetAllCategory
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Categories
    name: Categories
    href: Application.Categories.html
  - name: .
  - uid: Application.Categories.Queries
    name: Queries
    href: Application.Categories.Queries.html
  - name: .
  - uid: Application.Categories.Queries.GetAllCategory
    name: GetAllCategory
    href: Application.Categories.Queries.GetAllCategory.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Categories
    name: Categories
    href: Application.Categories.html
  - name: .
  - uid: Application.Categories.Queries
    name: Queries
    href: Application.Categories.Queries.html
  - name: .
  - uid: Application.Categories.Queries.GetAllCategory
    name: GetAllCategory
    href: Application.Categories.Queries.GetAllCategory.html
