### YamlMime:ManagedReference
items:
- uid: Application.Lookups.Queries.Languages.GetLanguages
  commentId: N:Application.Lookups.Queries.Languages.GetLanguages
  id: Application.Lookups.Queries.Languages.GetLanguages
  children:
  - Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQuery
  - Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryHandler
  - Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult
  langs:
  - csharp
  - vb
  name: Application.Lookups.Queries.Languages.GetLanguages
  nameWithType: Application.Lookups.Queries.Languages.GetLanguages
  fullName: Application.Lookups.Queries.Languages.GetLanguages
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQuery
  commentId: T:Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQuery
  parent: Application.Lookups.Queries.Languages.GetLanguages
  href: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQuery.html
  name: GetLanguagesQuery
  nameWithType: GetLanguagesQuery
  fullName: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQuery
- uid: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryHandler
  commentId: T:Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryHandler
  href: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryHandler.html
  name: GetLanguagesQueryHandler
  nameWithType: GetLanguagesQueryHandler
  fullName: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryHandler
- uid: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult
  commentId: T:Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult
  href: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult.html
  name: GetLanguagesQueryResult
  nameWithType: GetLanguagesQueryResult
  fullName: Application.Lookups.Queries.Languages.GetLanguages.GetLanguagesQueryResult
- uid: Application.Lookups.Queries.Languages.GetLanguages
  commentId: N:Application.Lookups.Queries.Languages.GetLanguages
  href: Application.html
  name: Application.Lookups.Queries.Languages.GetLanguages
  nameWithType: Application.Lookups.Queries.Languages.GetLanguages
  fullName: Application.Lookups.Queries.Languages.GetLanguages
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Lookups
    name: Lookups
    href: Application.Lookups.html
  - name: .
  - uid: Application.Lookups.Queries
    name: Queries
    href: Application.Lookups.Queries.html
  - name: .
  - uid: Application.Lookups.Queries.Languages
    name: Languages
    href: Application.Lookups.Queries.Languages.html
  - name: .
  - uid: Application.Lookups.Queries.Languages.GetLanguages
    name: GetLanguages
    href: Application.Lookups.Queries.Languages.GetLanguages.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Lookups
    name: Lookups
    href: Application.Lookups.html
  - name: .
  - uid: Application.Lookups.Queries
    name: Queries
    href: Application.Lookups.Queries.html
  - name: .
  - uid: Application.Lookups.Queries.Languages
    name: Languages
    href: Application.Lookups.Queries.Languages.html
  - name: .
  - uid: Application.Lookups.Queries.Languages.GetLanguages
    name: GetLanguages
    href: Application.Lookups.Queries.Languages.GetLanguages.html
