### YamlMime:ManagedReference
items:
- uid: Application.Commons.SharedModelResult
  commentId: N:Application.Commons.SharedModelResult
  id: Application.Commons.SharedModelResult
  children:
  - Application.Commons.SharedModelResult.LanguageResult
  - Application.Commons.SharedModelResult.QuestionSourceResult
  - Application.Commons.SharedModelResult.TagResult
  langs:
  - csharp
  - vb
  name: Application.Commons.SharedModelResult
  nameWithType: Application.Commons.SharedModelResult
  fullName: Application.Commons.SharedModelResult
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Commons.SharedModelResult.LanguageResult
  commentId: T:Application.Commons.SharedModelResult.LanguageResult
  parent: Application.Commons.SharedModelResult
  href: Application.Commons.SharedModelResult.LanguageResult.html
  name: LanguageResult
  nameWithType: LanguageResult
  fullName: Application.Commons.SharedModelResult.LanguageResult
- uid: Application.Commons.SharedModelResult.QuestionSourceResult
  commentId: T:Application.Commons.SharedModelResult.QuestionSourceResult
  href: Application.Commons.SharedModelResult.QuestionSourceResult.html
  name: QuestionSourceResult
  nameWithType: QuestionSourceResult
  fullName: Application.Commons.SharedModelResult.QuestionSourceResult
- uid: Application.Commons.SharedModelResult.TagResult
  commentId: T:Application.Commons.SharedModelResult.TagResult
  href: Application.Commons.SharedModelResult.TagResult.html
  name: TagResult
  nameWithType: TagResult
  fullName: Application.Commons.SharedModelResult.TagResult
- uid: Application.Commons.SharedModelResult
  commentId: N:Application.Commons.SharedModelResult
  href: Application.html
  name: Application.Commons.SharedModelResult
  nameWithType: Application.Commons.SharedModelResult
  fullName: Application.Commons.SharedModelResult
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.SharedModelResult
    name: SharedModelResult
    href: Application.Commons.SharedModelResult.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Commons
    name: Commons
    href: Application.Commons.html
  - name: .
  - uid: Application.Commons.SharedModelResult
    name: SharedModelResult
    href: Application.Commons.SharedModelResult.html
