### YamlMime:ManagedReference
items:
- uid: Application.Tags.Commands.AddTag
  commentId: N:Application.Tags.Commands.AddTag
  id: Application.Tags.Commands.AddTag
  children:
  - Application.Tags.Commands.AddTag.AddTagCommand
  - Application.Tags.Commands.AddTag.AddTagCommandHandler
  - Application.Tags.Commands.AddTag.AddTagCommandResult
  - Application.Tags.Commands.AddTag.AddTagCommandValidator
  langs:
  - csharp
  - vb
  name: Application.Tags.Commands.AddTag
  nameWithType: Application.Tags.Commands.AddTag
  fullName: Application.Tags.Commands.AddTag
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Tags.Commands.AddTag.AddTagCommand
  commentId: T:Application.Tags.Commands.AddTag.AddTagCommand
  parent: Application.Tags.Commands.AddTag
  href: Application.Tags.Commands.AddTag.AddTagCommand.html
  name: AddTagCommand
  nameWithType: AddTagCommand
  fullName: Application.Tags.Commands.AddTag.AddTagCommand
- uid: Application.Tags.Commands.AddTag.AddTagCommandHandler
  commentId: T:Application.Tags.Commands.AddTag.AddTagCommandHandler
  href: Application.Tags.Commands.AddTag.AddTagCommandHandler.html
  name: AddTagCommandHandler
  nameWithType: AddTagCommandHandler
  fullName: Application.Tags.Commands.AddTag.AddTagCommandHandler
- uid: Application.Tags.Commands.AddTag.AddTagCommandResult
  commentId: T:Application.Tags.Commands.AddTag.AddTagCommandResult
  href: Application.Tags.Commands.AddTag.AddTagCommandResult.html
  name: AddTagCommandResult
  nameWithType: AddTagCommandResult
  fullName: Application.Tags.Commands.AddTag.AddTagCommandResult
- uid: Application.Tags.Commands.AddTag.AddTagCommandValidator
  commentId: T:Application.Tags.Commands.AddTag.AddTagCommandValidator
  href: Application.Tags.Commands.AddTag.AddTagCommandValidator.html
  name: AddTagCommandValidator
  nameWithType: AddTagCommandValidator
  fullName: Application.Tags.Commands.AddTag.AddTagCommandValidator
- uid: Application.Tags.Commands.AddTag
  commentId: N:Application.Tags.Commands.AddTag
  href: Application.html
  name: Application.Tags.Commands.AddTag
  nameWithType: Application.Tags.Commands.AddTag
  fullName: Application.Tags.Commands.AddTag
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Tags
    name: Tags
    href: Application.Tags.html
  - name: .
  - uid: Application.Tags.Commands
    name: Commands
    href: Application.Tags.Commands.html
  - name: .
  - uid: Application.Tags.Commands.AddTag
    name: AddTag
    href: Application.Tags.Commands.AddTag.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Tags
    name: Tags
    href: Application.Tags.html
  - name: .
  - uid: Application.Tags.Commands
    name: Commands
    href: Application.Tags.Commands.html
  - name: .
  - uid: Application.Tags.Commands.AddTag
    name: AddTag
    href: Application.Tags.Commands.AddTag.html
