### YamlMime:ManagedReference
items:
- uid: Application.Commons.MappingConfig
  commentId: N:Application.Commons.MappingConfig
  id: Application.Commons.MappingConfig
  children:
  - Application.Commons.MappingConfig.CategoryMapper
  - Application.Commons.MappingConfig.SourceMapper
  - Application.Commons.MappingConfig.TagMapper
  langs:
  - csharp
  - vb
  name: Application.Commons.MappingConfig
  nameWithType: Application.Commons.MappingConfig
  fullName: Application.Commons.MappingConfig
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Commons.MappingConfig.CategoryMapper
  commentId: T:Application.Commons.MappingConfig.CategoryMapper
  href: Application.Commons.MappingConfig.CategoryMapper.html
  name: CategoryMapper
  nameWithType: CategoryMapper
  fullName: Application.Commons.MappingConfig.CategoryMapper
- uid: Application.Commons.MappingConfig.SourceMapper
  commentId: T:Application.Commons.MappingConfig.SourceMapper
  href: Application.Commons.MappingConfig.SourceMapper.html
  name: SourceMapper
  nameWithType: SourceMapper
  fullName: Application.Commons.MappingConfig.SourceMapper
- uid: Application.Commons.MappingConfig.TagMapper
  commentId: T:Application.Commons.MappingConfig.TagMapper
  href: Application.Commons.MappingConfig.TagMapper.html
  name: TagMapper
  nameWithType: TagMapper
  fullName: Application.Commons.MappingConfig.TagMapper
