### YamlMime:ManagedReference
items:
- uid: Domain.Repositories.IApplicationLogRepository
  commentId: T:Domain.Repositories.IApplicationLogRepository
  id: IApplicationLogRepository
  parent: Domain.Repositories
  children:
  - Domain.Repositories.IApplicationLogRepository.Count
  - Domain.Repositories.IApplicationLogRepository.GetAll(System.Func{Domain.Auditing.ApplicationLog,System.Boolean},System.Int32,System.Int32)
  langs:
  - csharp
  - vb
  name: IApplicationLogRepository
  nameWithType: IApplicationLogRepository
  fullName: Domain.Repositories.IApplicationLogRepository
  type: Interface
  source:
    remote:
      path: src/Domain/Repositories/IApplicationLogRepository.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: IApplicationLogRepository
    path: src/Domain/Repositories/IApplicationLogRepository.cs
    startLine: 4
  assemblies:
  - Domain
  namespace: Domain.Repositories
  syntax:
    content: public interface IApplicationLogRepository
    content.vb: Public Interface IApplicationLogRepository
  extensionMethods:
  - System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  - System.Object.Domain.Extentions.ObjectExtention.IsNull
- uid: Domain.Repositories.IApplicationLogRepository.GetAll(System.Func{Domain.Auditing.ApplicationLog,System.Boolean},System.Int32,System.Int32)
  commentId: M:Domain.Repositories.IApplicationLogRepository.GetAll(System.Func{Domain.Auditing.ApplicationLog,System.Boolean},System.Int32,System.Int32)
  id: GetAll(System.Func{Domain.Auditing.ApplicationLog,System.Boolean},System.Int32,System.Int32)
  parent: Domain.Repositories.IApplicationLogRepository
  langs:
  - csharp
  - vb
  name: GetAll(Func<ApplicationLog, bool>, int, int)
  nameWithType: IApplicationLogRepository.GetAll(Func<ApplicationLog, bool>, int, int)
  fullName: Domain.Repositories.IApplicationLogRepository.GetAll(System.Func<Domain.Auditing.ApplicationLog, bool>, int, int)
  type: Method
  source:
    remote:
      path: src/Domain/Repositories/IApplicationLogRepository.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: GetAll
    path: src/Domain/Repositories/IApplicationLogRepository.cs
    startLine: 6
  assemblies:
  - Domain
  namespace: Domain.Repositories
  syntax:
    content: IEnumerable<ApplicationLog> GetAll(Func<ApplicationLog, bool> func, int pageNumber, int pageSize)
    parameters:
    - id: func
      type: System.Func{Domain.Auditing.ApplicationLog,System.Boolean}
    - id: pageNumber
      type: System.Int32
    - id: pageSize
      type: System.Int32
    return:
      type: System.Collections.Generic.IEnumerable{Domain.Auditing.ApplicationLog}
    content.vb: Function GetAll(func As Func(Of ApplicationLog, Boolean), pageNumber As Integer, pageSize As Integer) As IEnumerable(Of ApplicationLog)
  overload: Domain.Repositories.IApplicationLogRepository.GetAll*
  nameWithType.vb: IApplicationLogRepository.GetAll(Func(Of ApplicationLog, Boolean), Integer, Integer)
  fullName.vb: Domain.Repositories.IApplicationLogRepository.GetAll(System.Func(Of Domain.Auditing.ApplicationLog, Boolean), Integer, Integer)
  name.vb: GetAll(Func(Of ApplicationLog, Boolean), Integer, Integer)
- uid: Domain.Repositories.IApplicationLogRepository.Count
  commentId: M:Domain.Repositories.IApplicationLogRepository.Count
  id: Count
  parent: Domain.Repositories.IApplicationLogRepository
  langs:
  - csharp
  - vb
  name: Count()
  nameWithType: IApplicationLogRepository.Count()
  fullName: Domain.Repositories.IApplicationLogRepository.Count()
  type: Method
  source:
    remote:
      path: src/Domain/Repositories/IApplicationLogRepository.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Count
    path: src/Domain/Repositories/IApplicationLogRepository.cs
    startLine: 7
  assemblies:
  - Domain
  namespace: Domain.Repositories
  syntax:
    content: int Count()
    return:
      type: System.Int32
    content.vb: Function Count() As Integer
  overload: Domain.Repositories.IApplicationLogRepository.Count*
references:
- uid: Domain.Repositories
  commentId: N:Domain.Repositories
  href: Domain.html
  name: Domain.Repositories
  nameWithType: Domain.Repositories
  fullName: Domain.Repositories
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Repositories
    name: Repositories
    href: Domain.Repositories.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Repositories
    name: Repositories
    href: Domain.Repositories.html
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions.ObjectExtention
  commentId: T:Domain.Extentions.ObjectExtention
  parent: Domain.Extentions
  href: Domain.Extentions.ObjectExtention.html
  name: ObjectExtention
  nameWithType: ObjectExtention
  fullName: Domain.Extentions.ObjectExtention
- uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions
  commentId: N:Domain.Extentions
  href: Domain.html
  name: Domain.Extentions
  nameWithType: Domain.Extentions
  fullName: Domain.Extentions
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
- uid: Domain.Repositories.IApplicationLogRepository.GetAll*
  commentId: Overload:Domain.Repositories.IApplicationLogRepository.GetAll
  href: Domain.Repositories.IApplicationLogRepository.html#Domain_Repositories_IApplicationLogRepository_GetAll_System_Func_Domain_Auditing_ApplicationLog_System_Boolean__System_Int32_System_Int32_
  name: GetAll
  nameWithType: IApplicationLogRepository.GetAll
  fullName: Domain.Repositories.IApplicationLogRepository.GetAll
- uid: System.Func{Domain.Auditing.ApplicationLog,System.Boolean}
  commentId: T:System.Func{Domain.Auditing.ApplicationLog,System.Boolean}
  parent: System
  definition: System.Func`2
  href: https://learn.microsoft.com/dotnet/api/system.func-2
  name: Func<ApplicationLog, bool>
  nameWithType: Func<ApplicationLog, bool>
  fullName: System.Func<Domain.Auditing.ApplicationLog, bool>
  nameWithType.vb: Func(Of ApplicationLog, Boolean)
  fullName.vb: System.Func(Of Domain.Auditing.ApplicationLog, Boolean)
  name.vb: Func(Of ApplicationLog, Boolean)
  spec.csharp:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: <
  - uid: Domain.Auditing.ApplicationLog
    name: ApplicationLog
    href: Domain.Auditing.ApplicationLog.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: '>'
  spec.vb:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: (
  - name: Of
  - name: " "
  - uid: Domain.Auditing.ApplicationLog
    name: ApplicationLog
    href: Domain.Auditing.ApplicationLog.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System.Collections.Generic.IEnumerable{Domain.Auditing.ApplicationLog}
  commentId: T:System.Collections.Generic.IEnumerable{Domain.Auditing.ApplicationLog}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<ApplicationLog>
  nameWithType: IEnumerable<ApplicationLog>
  fullName: System.Collections.Generic.IEnumerable<Domain.Auditing.ApplicationLog>
  nameWithType.vb: IEnumerable(Of ApplicationLog)
  fullName.vb: System.Collections.Generic.IEnumerable(Of Domain.Auditing.ApplicationLog)
  name.vb: IEnumerable(Of ApplicationLog)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: Domain.Auditing.ApplicationLog
    name: ApplicationLog
    href: Domain.Auditing.ApplicationLog.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: Domain.Auditing.ApplicationLog
    name: ApplicationLog
    href: Domain.Auditing.ApplicationLog.html
  - name: )
- uid: System.Func`2
  commentId: T:System.Func`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.func-2
  name: Func<T, TResult>
  nameWithType: Func<T, TResult>
  fullName: System.Func<T, TResult>
  nameWithType.vb: Func(Of T, TResult)
  fullName.vb: System.Func(Of T, TResult)
  name.vb: Func(Of T, TResult)
  spec.csharp:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: <
  - name: T
  - name: ','
  - name: " "
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: ','
  - name: " "
  - name: TResult
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Domain.Repositories.IApplicationLogRepository.Count*
  commentId: Overload:Domain.Repositories.IApplicationLogRepository.Count
  href: Domain.Repositories.IApplicationLogRepository.html#Domain_Repositories_IApplicationLogRepository_Count
  name: Count
  nameWithType: IApplicationLogRepository.Count
  fullName: Domain.Repositories.IApplicationLogRepository.Count
