### YamlMime:ManagedReference
items:
- uid: Domain.Auditing.ApplicationLog
  commentId: T:Domain.Auditing.ApplicationLog
  id: ApplicationLog
  parent: Domain.Auditing
  children:
  - Domain.Auditing.ApplicationLog.Exception
  - Domain.Auditing.ApplicationLog.Id
  - Domain.Auditing.ApplicationLog.Level
  - Domain.Auditing.ApplicationLog.Message
  - Domain.Auditing.ApplicationLog.Properties
  - Domain.Auditing.ApplicationLog.Timestamp
  langs:
  - csharp
  - vb
  name: ApplicationLog
  nameWithType: ApplicationLog
  fullName: Domain.Auditing.ApplicationLog
  type: Class
  source:
    remote:
      path: src/Domain/Auditing/ApplicationLog.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: ApplicationLog
    path: src/Domain/Auditing/ApplicationLog.cs
    startLine: 4
  assemblies:
  - Domain
  namespace: Domain.Auditing
  syntax:
    content: public class ApplicationLog
    content.vb: Public Class ApplicationLog
  inheritance:
  - System.Object
  extensionMethods:
  - System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  - System.Object.Domain.Extentions.ObjectExtention.IsNull
- uid: Domain.Auditing.ApplicationLog.Id
  commentId: P:Domain.Auditing.ApplicationLog.Id
  id: Id
  parent: Domain.Auditing.ApplicationLog
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: ApplicationLog.Id
  fullName: Domain.Auditing.ApplicationLog.Id
  type: Property
  source:
    remote:
      path: src/Domain/Auditing/ApplicationLog.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Id
    path: src/Domain/Auditing/ApplicationLog.cs
    startLine: 6
  assemblies:
  - Domain
  namespace: Domain.Auditing
  syntax:
    content: public Guid Id { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property Id As Guid
  overload: Domain.Auditing.ApplicationLog.Id*
- uid: Domain.Auditing.ApplicationLog.Timestamp
  commentId: P:Domain.Auditing.ApplicationLog.Timestamp
  id: Timestamp
  parent: Domain.Auditing.ApplicationLog
  langs:
  - csharp
  - vb
  name: Timestamp
  nameWithType: ApplicationLog.Timestamp
  fullName: Domain.Auditing.ApplicationLog.Timestamp
  type: Property
  source:
    remote:
      path: src/Domain/Auditing/ApplicationLog.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Timestamp
    path: src/Domain/Auditing/ApplicationLog.cs
    startLine: 7
  assemblies:
  - Domain
  namespace: Domain.Auditing
  syntax:
    content: public DateTimeOffset Timestamp { get; set; }
    parameters: []
    return:
      type: System.DateTimeOffset
    content.vb: Public Property Timestamp As DateTimeOffset
  overload: Domain.Auditing.ApplicationLog.Timestamp*
- uid: Domain.Auditing.ApplicationLog.Message
  commentId: P:Domain.Auditing.ApplicationLog.Message
  id: Message
  parent: Domain.Auditing.ApplicationLog
  langs:
  - csharp
  - vb
  name: Message
  nameWithType: ApplicationLog.Message
  fullName: Domain.Auditing.ApplicationLog.Message
  type: Property
  source:
    remote:
      path: src/Domain/Auditing/ApplicationLog.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Message
    path: src/Domain/Auditing/ApplicationLog.cs
    startLine: 8
  assemblies:
  - Domain
  namespace: Domain.Auditing
  syntax:
    content: public string Message { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Message As String
  overload: Domain.Auditing.ApplicationLog.Message*
- uid: Domain.Auditing.ApplicationLog.Level
  commentId: P:Domain.Auditing.ApplicationLog.Level
  id: Level
  parent: Domain.Auditing.ApplicationLog
  langs:
  - csharp
  - vb
  name: Level
  nameWithType: ApplicationLog.Level
  fullName: Domain.Auditing.ApplicationLog.Level
  type: Property
  source:
    remote:
      path: src/Domain/Auditing/ApplicationLog.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Level
    path: src/Domain/Auditing/ApplicationLog.cs
    startLine: 9
  assemblies:
  - Domain
  namespace: Domain.Auditing
  syntax:
    content: public LogEventLevel Level { get; set; }
    parameters: []
    return:
      type: Serilog.Events.LogEventLevel
    content.vb: Public Property Level As LogEventLevel
  overload: Domain.Auditing.ApplicationLog.Level*
- uid: Domain.Auditing.ApplicationLog.Exception
  commentId: P:Domain.Auditing.ApplicationLog.Exception
  id: Exception
  parent: Domain.Auditing.ApplicationLog
  langs:
  - csharp
  - vb
  name: Exception
  nameWithType: ApplicationLog.Exception
  fullName: Domain.Auditing.ApplicationLog.Exception
  type: Property
  source:
    remote:
      path: src/Domain/Auditing/ApplicationLog.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Exception
    path: src/Domain/Auditing/ApplicationLog.cs
    startLine: 10
  assemblies:
  - Domain
  namespace: Domain.Auditing
  syntax:
    content: public ExceptionInfo? Exception { get; set; }
    parameters: []
    return:
      type: Domain.Auditing.ExceptionInfo
    content.vb: Public Property Exception As ExceptionInfo
  overload: Domain.Auditing.ApplicationLog.Exception*
- uid: Domain.Auditing.ApplicationLog.Properties
  commentId: P:Domain.Auditing.ApplicationLog.Properties
  id: Properties
  parent: Domain.Auditing.ApplicationLog
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: ApplicationLog.Properties
  fullName: Domain.Auditing.ApplicationLog.Properties
  type: Property
  source:
    remote:
      path: src/Domain/Auditing/ApplicationLog.cs
      branch: master
      repo: https://github.com/abdulazizAbabutain/Examiner.git
    id: Properties
    path: src/Domain/Auditing/ApplicationLog.cs
    startLine: 11
  assemblies:
  - Domain
  namespace: Domain.Auditing
  syntax:
    content: public IDictionary<string, string> Properties { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.String}
    content.vb: Public Property Properties As IDictionary(Of String, String)
  overload: Domain.Auditing.ApplicationLog.Properties*
references:
- uid: Domain.Auditing
  commentId: N:Domain.Auditing
  href: Domain.html
  name: Domain.Auditing
  nameWithType: Domain.Auditing
  fullName: Domain.Auditing
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Auditing
    name: Auditing
    href: Domain.Auditing.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Auditing
    name: Auditing
    href: Domain.Auditing.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNotNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Domain.Extentions.ObjectExtention.IsNull
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  parent: Domain.Extentions.ObjectExtention
  definition: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  name: IsNotNull(object)
  nameWithType: ObjectExtention.IsNotNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNotNull(object)
  nameWithType.vb: ObjectExtention.IsNotNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNotNull(Object)
  name.vb: IsNotNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNotNull(System.Object)
    name: IsNotNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNotNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions.ObjectExtention
  commentId: T:Domain.Extentions.ObjectExtention
  parent: Domain.Extentions
  href: Domain.Extentions.ObjectExtention.html
  name: ObjectExtention
  nameWithType: ObjectExtention
  fullName: Domain.Extentions.ObjectExtention
- uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
  commentId: M:Domain.Extentions.ObjectExtention.IsNull(System.Object)
  isExternal: true
  href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  name: IsNull(object)
  nameWithType: ObjectExtention.IsNull(object)
  fullName: Domain.Extentions.ObjectExtention.IsNull(object)
  nameWithType.vb: ObjectExtention.IsNull(Object)
  fullName.vb: Domain.Extentions.ObjectExtention.IsNull(Object)
  name.vb: IsNull(Object)
  spec.csharp:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Domain.Extentions.ObjectExtention.IsNull(System.Object)
    name: IsNull
    href: Domain.Extentions.ObjectExtention.html#Domain_Extentions_ObjectExtention_IsNull_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Domain.Extentions
  commentId: N:Domain.Extentions
  href: Domain.html
  name: Domain.Extentions
  nameWithType: Domain.Extentions
  fullName: Domain.Extentions
  spec.csharp:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
  spec.vb:
  - uid: Domain
    name: Domain
    href: Domain.html
  - name: .
  - uid: Domain.Extentions
    name: Extentions
    href: Domain.Extentions.html
- uid: Domain.Auditing.ApplicationLog.Id*
  commentId: Overload:Domain.Auditing.ApplicationLog.Id
  href: Domain.Auditing.ApplicationLog.html#Domain_Auditing_ApplicationLog_Id
  name: Id
  nameWithType: ApplicationLog.Id
  fullName: Domain.Auditing.ApplicationLog.Id
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: Domain.Auditing.ApplicationLog.Timestamp*
  commentId: Overload:Domain.Auditing.ApplicationLog.Timestamp
  href: Domain.Auditing.ApplicationLog.html#Domain_Auditing_ApplicationLog_Timestamp
  name: Timestamp
  nameWithType: ApplicationLog.Timestamp
  fullName: Domain.Auditing.ApplicationLog.Timestamp
- uid: System.DateTimeOffset
  commentId: T:System.DateTimeOffset
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.datetimeoffset
  name: DateTimeOffset
  nameWithType: DateTimeOffset
  fullName: System.DateTimeOffset
- uid: Domain.Auditing.ApplicationLog.Message*
  commentId: Overload:Domain.Auditing.ApplicationLog.Message
  href: Domain.Auditing.ApplicationLog.html#Domain_Auditing_ApplicationLog_Message
  name: Message
  nameWithType: ApplicationLog.Message
  fullName: Domain.Auditing.ApplicationLog.Message
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Domain.Auditing.ApplicationLog.Level*
  commentId: Overload:Domain.Auditing.ApplicationLog.Level
  href: Domain.Auditing.ApplicationLog.html#Domain_Auditing_ApplicationLog_Level
  name: Level
  nameWithType: ApplicationLog.Level
  fullName: Domain.Auditing.ApplicationLog.Level
- uid: Serilog.Events.LogEventLevel
  commentId: T:Serilog.Events.LogEventLevel
  parent: Serilog.Events
  isExternal: true
  name: LogEventLevel
  nameWithType: LogEventLevel
  fullName: Serilog.Events.LogEventLevel
- uid: Serilog.Events
  commentId: N:Serilog.Events
  isExternal: true
  name: Serilog.Events
  nameWithType: Serilog.Events
  fullName: Serilog.Events
  spec.csharp:
  - uid: Serilog
    name: Serilog
    isExternal: true
  - name: .
  - uid: Serilog.Events
    name: Events
    isExternal: true
  spec.vb:
  - uid: Serilog
    name: Serilog
    isExternal: true
  - name: .
  - uid: Serilog.Events
    name: Events
    isExternal: true
- uid: Domain.Auditing.ApplicationLog.Exception*
  commentId: Overload:Domain.Auditing.ApplicationLog.Exception
  href: Domain.Auditing.ApplicationLog.html#Domain_Auditing_ApplicationLog_Exception
  name: Exception
  nameWithType: ApplicationLog.Exception
  fullName: Domain.Auditing.ApplicationLog.Exception
- uid: Domain.Auditing.ExceptionInfo
  commentId: T:Domain.Auditing.ExceptionInfo
  parent: Domain.Auditing
  href: Domain.Auditing.ExceptionInfo.html
  name: ExceptionInfo
  nameWithType: ExceptionInfo
  fullName: Domain.Auditing.ExceptionInfo
- uid: Domain.Auditing.ApplicationLog.Properties*
  commentId: Overload:Domain.Auditing.ApplicationLog.Properties
  href: Domain.Auditing.ApplicationLog.html#Domain_Auditing_ApplicationLog_Properties
  name: Properties
  nameWithType: ApplicationLog.Properties
  fullName: Domain.Auditing.ApplicationLog.Properties
- uid: System.Collections.Generic.IDictionary{System.String,System.String}
  commentId: T:System.Collections.Generic.IDictionary{System.String,System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IDictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  name: IDictionary<string, string>
  nameWithType: IDictionary<string, string>
  fullName: System.Collections.Generic.IDictionary<string, string>
  nameWithType.vb: IDictionary(Of String, String)
  fullName.vb: System.Collections.Generic.IDictionary(Of String, String)
  name.vb: IDictionary(Of String, String)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.Collections.Generic.IDictionary`2
  commentId: T:System.Collections.Generic.IDictionary`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  name: IDictionary<TKey, TValue>
  nameWithType: IDictionary<TKey, TValue>
  fullName: System.Collections.Generic.IDictionary<TKey, TValue>
  nameWithType.vb: IDictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.IDictionary(Of TKey, TValue)
  name.vb: IDictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  - name: <
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2
  - name: (
  - name: Of
  - name: " "
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
